### ISSUE TITLE
Replace downshift with headless-ui

### ISSUE THREAD

**Issue by Pertempto** [arrocke/gloss-translation#106]
The input width has some kind of glitch occasionally. 

![image](https://github.com/arrocke/gloss-translation/assets/17209828/84a68a7c-710e-425c-ac08-e5404adc06cc)

**Comment by arrocke** [comment]
Instead of trying to fix this, we should replace `downshift` with the combobox from `headless-ui`. That should work better with tailwind.

**Comment by arrocke** [comment]
My branch (#113) has an example of headless ui for a multiselect component without typing to filter. We should make sure this one looks similar

**Comment by Pertempto** [comment]
Thanks for mentioning it 👍🏽

**Comment by Pertempto** [comment]
# To Do
- [x] support the `onCreate` prop
- [x] Remove the old `AutocompleteInput` component
- [x] Remove `downshift`
