### ISSUE TITLE
replace nextauth

### ISSUE THREAD

**Issue by arrocke** [arrocke/gloss-translation#108]
I'm not happy with next auth. It does the session management, and magic link stuff well, but it's very restricting. I can't send a magic link from the server, and it doesn't work well when put on a different domain. I'm going to look in to alternatives. We really just need a library to handle the authentication and session management, and we can handle all of the UI, and necessary emails.

[Lucia](https://lucia-auth.com/tokens/start-here/introduction?) looks promising, but it's relatively new. @Pertempto what do you think?

**Comment by Pertempto** [comment]
It looks promising! Instead of using a built-in sign-in page like we did with next auth, we'd need to develop our own? It looks like we'd have to develop more of the logic ourselves that was handled for us automatically with next auth, but the positive side of that is that we get more control.

**Comment by arrocke** [comment]
Lucia todo:
- [x] replace login/logout/session routes
- [x] add login view
- [x] replace user invite
- [x] login email
- [x] invite email
- [x] email followup page
- [x] document schema changes
- [x] update auth docs
- [x] vercel build issue
- [x] handle invalid tokens
- [x] add auth origins to env vars
