### ISSUE TITLE
long term hosting plan

### ISSUE THREAD

**Issue by arrocke** [arrocke/gloss-translation#112]
We are at our vercel limit, ~~and our auth solution isn't going to work with preview urls~~. We need to either decide to pay for vercel, or find an alternative solution for deployments. Let's discuss what we want and what we think we can manage here before we make decision

**Comment by arrocke** [comment]
@Pertempto What are your thoughts here? I want to look into terraform for managing our infrastructure to see if that can make AWS management approachable.

**Comment by arrocke** [comment]
I think I'm ok with letting go of preview apps in favor of just testing locally. I really like deploying to production from the main branch especially if we have a testing suite in the long run, but it may make sense to have an experimental environment with feature flags turned on while we develop in order to get feedback from testing users.

**Comment by Pertempto** [comment]
> I think I'm ok with letting go of preview apps in favor of just testing locally. 

Yeah, the preview apps are nice, but I have rarely used them. I'm used to testing PRs locally.

**Comment by Pertempto** [comment]
> @Pertempto What are your thoughts here? I want to look into terraform for managing our infrastructure to see if that can make AWS management approachable.

It sounds good to me. I am much more familiar with AWS than Vercel. I am in no way an AWS expert, but I've learned some of the basics in the last year or so.

**Comment by arrocke** [comment]
@Pertempto I think we may want to push this change off for now so that we can focus on other things. If you are still able to create preview deploys by pushing to a branch even though you aren't on the team, then I think $20/month is reasonable for the convenience. I still think we may want to move off in the long run

**Comment by Pertempto** [comment]
Yeah, since it is no longer blocking our auth system, that makes sense

**Comment by arrocke** [comment]
I was able to set up AWS amplify to build both the api and web from main. You can see the frontend [here](https://main.d1ajmok3mfjfeb.amplifyapp.com/languages/en/verses/01001001/), but it is talking to the vercel api server for now. The backend explorer is [here](https://main.d3q1l42h0vxhz5.amplifyapp.com/explorer). 

@Pertempto I think we should move forward with this. I can set up the domain in AWS to point to these amplify apps instead of vercel and then close that down. If you want to take a look at the configuration in AWS, you should have access. Let me know what you think.

**Comment by Pertempto** [comment]
It looks good to me!

**Comment by arrocke** [comment]
We are completely off vercel, so I'm going to consider this done
