### ISSUE TITLE
organize openAPI yml files

### ISSUE THREAD

**Issue by Pertempto** [arrocke/gloss-translation#122]
The openAPI yml files should be organized in a directory tree structure, instead of a flat structure.

**Comment by ilearner777** [comment]
Are you referring to the files in the packages/api/public/spec/paths directory? If so, what type of tree structure do you have in mind.

**Comment by Pertempto** [comment]
> Are you referring to the files in the packages/api/public/spec/paths directory?

Yes


> If so, what type of tree structure do you have in mind.

If you take a look, you'll see we already have `import` and `languages` sub-directories in that directory. The idea would be to move all the language-related docs into the `languages` directory, and create new sub-directories to categorize all the other docs. 

I'm just imagining a two-level tree structure, where the first level is all the "categories" of routes, and the second level is the route doc files themselves. The first level sub-directories will roughly mirror the tag listened in each doc file. This way the file structure of the docs file will roughly match the file structure of the routes themself in `packagages/api/pages/api`

**Comment by Pertempto** [comment]
@arrocke Does this sound reasonable?

**Comment by arrocke** [comment]
Yep! This is good with me. 

@ilearner777 Is this something you want to take on? I think it is a good first ticket which will give you familiarity with our api.

**Comment by ilearner777** [comment]
Yes.  Are you thinking of something like this:

api
  import/...
  languages/...
  routes
    authentication/ auth.yml
    users/ users.yml; verse-glosses.yml
    verses/ verse.yml
    language-import/ languages.yml; import.yml
    languages /language-member.yml; language-members.yml*; language..yml
    glosses/ language-words.yml
    default/ language-members.yml *

Note: file language-members.yml contains definition for 2 different categories. (languages and default).
We could split out the POST Invite a new member to a separate file and put it into the default directory.

Let me if the above is correct.

 (Right now I am setting up my local env, so can't work on it until I this complete and running.)

**Comment by arrocke** [comment]
@Pertempto curious what you were thinking, but for me we can use tags and category directories differently. These are the top level directories I'd use
* users - auth.yml, user(s).yml, verify-email.yml
* languages - language(s).yml, language-members(s).yml, language-words.yml, import/languages.yml, languages/import.yml (I'd rename this last two into a file name rather than a nested directory)
* translation - verse.yml, verse-glosses.yml, translations.yml

Then I'd tag things according to their top level URL collection, so languages, users, auth, verses, etc. I'd tag the verify email and import languages as a misc tag since they are one-offs

**Comment by Pertempto** [comment]
That is fine with me. The file structure isn't going to impact the final docs page at all, it's just a matter of whatever is easiest for us to maintain long-term.

From a consistency standpoint, should the third top-level directory be `translation` or `translations`? You used plural nouns for the first two, but maybe you are thinking of the third one in the verb form.

**Comment by ilearner777** [comment]
Hi All:  I will do whatever you ask as I am new to this project.  As an FYI....  My suggested file structure was based on the API explorer page: https://gloss-translation-api.vercel.app/explorer. I used the headings as my guide.

But as mention will use the one recommend by @arrocke .

**Comment by Pertempto** [comment]
Just FYI, those headings correspond to the tags field.

**Comment by arrocke** [comment]
The directory structure and tags serve different purposes. The directory structure is intended to make it easy to find the route you want to modify, while tags serve as groups in the explorer user interface. A route can have multiple tags which would allow the same route to appear in different groups in the UI.

**Comment by ilearner777** [comment]
Re comment:
```
import/languages.yml, languages/import.yml (I'd rename this last two into a file name rather than a nested directory)
```
Do you want file: `import/languages.yml` to be renamed: `import-languages.yml`
and
`languages/import.yml` to be renamed: `languages-import.yml`?

Then once renamed to be put into dir: `paths/languages`?

**Comment by arrocke** [comment]
Yep, that's what I had in mind

**Comment by ilearner777** [comment]
Below is the steps I plan to take. Please review and confirm if they are correct. Let me know if I have missed anything:
1.`rename`:  languages/import.yml -> languages-import.yml
2. `rename`: import/languages.yml -> import-languages.yml
3. `create dir`: users
4. `create dir`: translation
5. `move file`: import-languages.yml to `dir`: languages
6. `rm dir`: import
7. `move files`: auth.yml, user(s).yml, verify-email.yml -> `dir`: users
8. `move files`: language(s).yml, language-members(s).yml, language-words.yml -> `dir`: languages
9. `move files`: verse.yml, verse-glosses.yml, translations.yml -> `dir`: translation
10. `Edit file`: packages/api/public/spec/index.yml with new file locations.

**Comment by ilearner777** [comment]
Also: 
Once I have made these changes, what do I do, to test/debug my changes to make sure they are working correctly?

**Comment by ilearner777** [comment]
This is what the new folder hierarchy will look like. Let me know if this is correct.
![Issue#179 organize-api-yml](https://github.com/arrocke/gloss-translation/assets/141659916/51c51024-b6c0-4b16-8ee8-c643e094b2dc)

**Comment by ilearner777** [comment]
P.S. I found out that if I launch api that it will highlight any errors.  So I am good for testing code change.

**Comment by ilearner777** [comment]
I made the directory/file location changes to index.yml however I am getting the following errors shown below.
So there must be another something ellse that needs to be updated. Please advise.

``` 
Resolver error at paths./users/{user}.patch.parameters.0.$ref
Could not resolve reference: undefined undefined
Resolver error at paths./verses/{verseId}.get.parameters.0.$ref
Could not resolve reference: undefined undefined
Resolver error at paths./languages.get.responses.200.content.application/json.schema.properties.data.allOf.0.items.$ref
Could not resolve reference: undefined undefined
Resolver error at paths./languages.post.requestBody.content.application/json.schema.$ref
Could not resolve reference: undefined undefined
Resolver error at paths./languages.get.responses.200.content.application/json.schema.properties.data.items.$ref
Could not resolve reference: undefined undefined
Resolver error at paths./languages.get.responses.200.content.application/json.schema.properties.data.items.$ref
Could not resolve reference: undefined undefined
Resolver error at paths./languages/{code}.get.parameters.0.$ref
Could not resolve reference: undefined undefined
Resolver error at paths./languages/{code}.get.responses.200.content.application/json.schema.properties.data.$ref
Could not resolve reference: undefined undefined
Resolver error at paths./languages/{code}.patch.parameters.0.$ref
Could not resolve reference: undefined undefined
Resolver error at paths./languages/{code}/verses/{verseId}/translation.get.parameters.0.$ref
Could not resolve reference: undefined undefined
Resolver error at paths./languages/{code}/verses/{verseId}/translation.get.parameters.1.$ref
Could not resolve reference: undefined undefined
Resolver error at paths./languages/{code}/verses/{verseId}/glosses.get.parameters.0.$ref
Could not resolve reference: undefined undefined
Resolver error at paths./languages/{code}/verses/{verseId}/glosses.get.parameters.1.$ref
Could not resolve reference: undefined undefined
Resolver error at paths./languages/{code}/words/{wordId}.patch.parameters.0.$ref
Could not resolve reference: undefined undefined
Resolver error at paths./languages/{code}/words/{wordId}.patch.parameters.1.$ref
Could not resolve reference: undefined undefined
Resolver error at paths./languages/{code}/members.get.parameters.0.$ref
Could not resolve reference: undefined undefined
Resolver error at paths./languages/{code}/members.post.parameters.0.$ref
Could not resolve reference: undefined undefined
Resolver error at paths./languages/{code}/members/{userId}.patch.parameters.0.$ref
Could not resolve reference: undefined undefined
Resolver error at paths./languages/{code}/members/{userId}.patch.parameters.1.$ref
Could not resolve reference: undefined undefined
Resolver error at paths./languages/{code}/members/{userId}.delete.parameters.0.$ref
Could not resolve reference: undefined undefined
Resolver error at paths./languages/{code}/members/{userId}.delete.parameters.1.$ref
Could not resolve reference: undefined undefined
```

**Comment by Pertempto** [comment]
> Also: Once I have made these changes, what do I do, to test/debug my changes to make sure they are working correctly?

Run the API and access the API docs at http://localhost:4300/explorer to make sure everything still works.

**Comment by Pertempto** [comment]
> I made the directory/file location changes to index.yml however I am getting the following errors shown below. So there must be another something ellse that needs to be updated. Please advise.


This is the kind of question that is better asked in a draft PR, so that it's easier for us to see what's going on. A draft PR is a good way to get feedback while you work on an issue.

**Comment by Pertempto** [comment]
@ilearner777 I moved this to "In Review". In the future, don't forget to move issues to "in progress" and "in review" as you work them through their various stages.
