### ISSUE TITLE
Switch to postmark for sending emails

### ISSUE THREAD

**Issue by arrocke** [arrocke/gloss-translation#124]
I'm not able to get SES production access without a bunch more work. They won't even tell me what I need to do. I propose we switch to postmark for email delivery. They are a transactional email service that I've used in the past that I like. 100 emails a month are free, and after that its $15 for 10,000 emails a month. I think if we switch to passwords for authentication we could stay in that free tier for a while

**Comment by arrocke** [comment]
@Pertempto What do you think about this?

**Comment by Pertempto** [comment]
My only reservation is that we invested a lot of work into the email link login system so it doesn't sound great to scrap all that. How much rework will be involved in switching to a password system?

It would also be interesting to look at using third party auth tools like sign in with Google. That definitely shouldn't be our primary system but it could be useful to our users in that they don't have to create another password.

**Comment by arrocke** [comment]
With lucia, it won't be too bad. We just need to ask for a password on invite accept, and check it with the login screen and route. At this point the investment is a sunk cost so here is how I'm thinking about it.
1. We can move to postmark for email sending. This is pretty simple: set up postmark and point our sever to their SMTP server rather than AWS. This much is a no brainer at this point, since getting AWS to let us send emails is pretty difficult
2. The reasons we would switch to passwords are separate. Either to save money or because we think the user experience is better. Frankly after using the magic links for a while, I don't prefer them because my password manager has made logging in with a password a breeze.

**Comment by Pertempto** [comment]
Sounds good to me! I'm fine with using passwords for login

**Comment by arrocke** [comment]
Lol, after I sent a frustrated response in the support ticket about their process, they gave us access. I'm going to close this

**Comment by Pertempto** [comment]
> Lol, after I sent a frustrated response in the support ticket about their process, they gave us access. I'm going to close this

Hahaha, nice!
