### ISSUE TITLE
vercel prevents import request from completing

### ISSUE THREAD

**Issue by arrocke** [arrocke/gloss-translation#134]
**Describe the bug**

Vercel has a 10-60 second runtime limit for requests. Our import request takes a few minutes to run because there is so much data.

**To Reproduce**

1. Log in as a language or platform admin
2. Go to the manage language page
3. Import glosses
4. Observe 504 timeout error

**Expected behavior**

The import should take a while, but it should complete.

**Comment by Pertempto** [comment]
tomorrow morning I might have time to run a few tests on my local machine to get an idea about what fraction of the time is spent on each task (deleting glosses, network loading, parsing, adding glosses)

**Comment by arrocke** [comment]
If we were to use AWS lambda for this, here is how it could work:
1. React client makes request to `/api/languages/:code/import`
2. Server invokes the lambda function which does all of the work, creates a record in the database for the import progress with a unique token and returns 202 accepted
3. Lambda updates the import db record indicating that the import is complete
4. React client polls `/api/languages/:code/import` for the status of the job which eventually will indicate that the job is complete.

```mermaid
sequenceDiagram
    Web->>API: POST /languages/:code/import
    activate API
    API->>API: create import job in database
    API->>AWS Lambda: start job in lambda
    activate AWS Lambda
    API->>Web: Return 202
    deactivate API

    Web->>API: GET /languages/:code/import
    activate API
    API->>Web: Return 200 in-progress
    deactivate API

    AWS Lambda->>AWS Lambda: mark job as complete
    deactivate AWS Lambda
    
    Web->>API: GET /languages/:code/import
    activate API
    API->>Web: Return 200 done
    deactivate API
```

**Comment by Pertempto** [comment]
It would be great if the record in the database should include some kind of progress value. Then when the frontend polls the backend, it can at least get a progress value to show to the user, so that they can see how much of the import is complete.

Why do we need the `/languages/:code/import/complete` API route? Why can't the lambda just update the database record to indicate that the import is complete?

**Comment by Pertempto** [comment]
In my rough tests, the various parts of import take up this much of the total import time:
| Task | Fraction |
|-|-|
| Delete old glosses | ~30% |
| Fetch data | ~28%   |
| Parse data |  ~2%  |
| Insert new glosses |  ~39%  |
| Other processing  | ~0.4%   |


I tested with Arabic, which only has OT glosses. A full Bible of glosses would change the stats slightly, but it doesn't sound like it will be a normal use case to import the whole Bible, seeing that the old site doesn't seem to have any full Bible gloss datasets. The total import time was about 55-58 seconds.


My process was
- Import Arabic
- Run import again (so full delete process)
- Record stats

If you recorded the stats for a brand new import, the delete time would be basically 0.

**Comment by Pertempto** [comment]
If we use the polling strategy, it seems that once every 10 seconds would be reasonable. Languages with less glosses (or brand new imports) will take less time than the rough minute it takes for a whole OT replacement import.

**Comment by arrocke** [comment]
Yeah I think you are right that we don't need that extra API route since the lambda can just do it. If we want that to update progress then we might want a smaller poll interval like 4 or 5 seconds. We can play around with that.

I've never deployed from nx to lambda, but they have some docs here: https://nx.dev/recipes/node/node-aws-lambda

**Comment by Pertempto** [comment]
Did you want me to do this one? I have zero experience with lambda, but I'm willing to learn.

**Comment by Pertempto** [comment]
I'll follow the steps in the docs to try to setup lambda in the project.

**Comment by Pertempto** [comment]
Just fyi, running lambda functions locally requires the SAM cli from Amazon and docker. Two more things our developers will have to install.

**Comment by arrocke** [comment]
I don't have any experience with lambda either, so I'd say go for it. I don't think the extra install is a super big deal, it should be temporary since eventually, this will be the only app. I also updated the workflow up top with your suggestion to remove the unnecessary route

**Comment by Pertempto** [comment]
> it should be temporary since eventually, this will be the only app

What do you mean by "this will be the only app"?

**Comment by arrocke** [comment]
Once everyone migrates from the old app, we won't need to import anymore
