### ISSUE TITLE
Manage Language Should Switch Context

### ISSUE THREAD

**Issue by Pertempto** [arrocke/gloss-translation#135]
**Is your feature request related to a problem? Please describe.**
It always feel strange to go to the manage language page for a language, then click the translate button and it goes back to a different language.

**Describe the solution you'd like**
Going to the manage language page should update the `translation-language` value in local storage, so that you are now in the subset of the site related to that language. Clicking the translate button in the header from the manage language page should now take you to the translate page for that language.

**Comment by arrocke** [comment]
Since the selected language is a setting for one view, what do you think about moving the selected language for translation out of the header? Then the header would be `Translate Languages Users Profile` depending on what you have access to. You can put the selected language on the same line as the verse selector

**Comment by arrocke** [comment]
I went ahead and made this change when I worked on the error page. Let me know what you think of how I solved this in #143

**Comment by Pertempto** [comment]
> Since the selected language is a setting for one view, what do you think about moving the selected language for translation out of the header? Then the header would be `Translate Languages Users Profile` depending on what you have access to. You can put the selected language on the same line as the verse selector

The way it was setup now, I didn't know the setting was for one view. The fact that we store it in local storage and display it in the global header made it seem very much like a global setting.

If it should be a setting for one view, I think we should really put it in the URL. Something like `:languageCode/translate/:verseId?` instead of `translate/:verseId?`
