### ISSUE TITLE
Separate email verification from users

### ISSUE THREAD

**Issue by arrocke** [arrocke/gloss-translation#141]
**Is your feature request related to a problem? Please describe.**
In #140 we are sending emails to addresses that aren't associated with a user. This happens because we want to verify an email address before we attach it to a user, or because we want to send a notification to the previous email when it is changed by a user. This means we should separate users and verified emails in the database.

**Describe the solution you'd like**
1. A new database table called `EmailVerification` with two columns `email` and `status`. `status` can be `VERIFIED`, `BOUNCED`, or `COMPLAINED`. This would replace the email verification column on the `AuthUser` table.
2. When we send an email we can look up the address against this table and only send if the status is verified.

**Comment by arrocke** [comment]
@Pertempto Can you take a look at this and let me know what you think?

**Comment by Pertempto** [comment]
It makes sense to me.

**Comment by Pertempto** [comment]
How does
> When we send an email we can look up the address against this table and only send if the status is verified.


apply when a user is added to the system or updates their email address? In both cases we would need to send an email to an unverified email.

**Comment by arrocke** [comment]
Yeah, there is a parameter to override the verification before sending the email. We'll need to use that, but only to allow us to send to addresses that we haven't tracked yet. It should still prevent sending the emails to addresses that bounced or complained
