### ISSUE TITLE
localization strategy

### ISSUE THREAD

**Issue by arrocke** [arrocke/gloss-translation#142]
After using react-i18next a bit, I think we can improve a few things.

* Create a `common` namespace for keys that could be used on any view. For example: `Submit`, `Next`, `Back`
* Create new namespaces for keys that are limited to a subdomain of the app. For example: the users namespace could have the keys for `Email` and `Password`, but perhaps the the key for `Name` is in the common namespace since that can be used by languages.
* Require components to use the full namespace when specifying translation keys. That makes it easier to add a namespace later since no keys are assuming a default namespace.
* Sort the translation keys in alphabetical order

**Comment by arrocke** [comment]
@Pertempto Another one that I'd like you to give feedback on. No rush

**Comment by Pertempto** [comment]
I think this is a great idea!

**Comment by Pertempto** [comment]
I think we should also define some kind of ordering of keys in the translation JSON files.

**Comment by arrocke** [comment]
What do you think about alphabetical? That makes things easy to find, and doesn't require any judgement calls

**Comment by Pertempto** [comment]
Yeah, that's what I would do.

**Comment by Pertempto** [comment]
I think I can handle this one, the only one I'm not sure about is

> Require components to use the full namespace when specifying translation keys.

but I hope to figure it out as I go

**Comment by arrocke** [comment]
Right now, you can specify a default namespace when you call `useTranslation`, so that if a namespace isn't used (ie `gen` vs `bible:gen`), it will use the default you gave it. I want to always use a namespace when we use the `t` function so that it is easy to add and remove namespaces from a component without having to update all of the keys. It's also then easier to figure out which namespace that key is in

**Comment by Pertempto** [comment]
But how do I implement that enforcement? I tried setting `defaultNS` to `false`, like the [docs stated](https://www.i18next.com/overview/configuration-options), but I don't get any errors about the `t` calls that don't specify a namespace

**Comment by Pertempto** [comment]
I think we should use `translate.json` for the terms related to the translate feature, because `translation.json` is the default name used by `i18next`

**Comment by arrocke** [comment]
> But how do I implement that enforcement? I tried setting defaultNS to false, like the [docs stated](https://www.i18next.com/overview/configuration-options), but I don't get any errors about the t calls that don't specify a namespace

I don't think we need enforcement, we can handle that in review

**Comment by Pertempto** [comment]
## To Do
- [x] Reorganize non-english translation files
- [x] Alphabetize
