### ISSUE TITLE
nx: command not found

### ISSUE THREAD

**Issue by ilearner777** [arrocke/gloss-translation#152]
**Describe the bug**
Was following instructions in `db.md`. Got a `nx: command not found` error when trying to run:
``` bash
nx prisma db migrate reset
```

**To Reproduce**
1. Fork repo
2. Install node.js
3. Install postgresql
4. Create local database
5. Set DATABASE_URL
6. Run in bash: `nx prisma db migrate reset`

**Expected behavior**
Expect command to run or instructions on how to configure local env to enable it to run.

**Screenshots**

**Environment (please complete the following information):**
- Laptop
- OS: Windows 11

**Additional context**
I discovered the answer to my problem in the `contributing.md` document.  You can close this issue. `nx` works now!

**Suggestions**
Perhaps we can reorder the sequence of steps in `contributing.md` and `db.md` to avoid the confusion I ran into.
Example:
1. Put these lines ***before*** the instructions for db install:
``` 
Run `npm install` to install all of the project's dependencies. 
Run `npm i -g nx` to make the `nx` command available in the terminal.
```
2.  Modify this line as follows and move ***before*** db install instruction but ***after*** above 2 lines.
```
Copy of `.env` file and rename it  `.env.local` file in the `api` package directory. 
Setup`env.local` as required. Instructions for setting the mandatory env var: `DATABASE_URL` are found in file `db.md`.
```
3. Move this line to the end of the `db.md` file:
```
Run `pg_restore -Fc --format=custom --dbname=<connection-string> data/seed.dump` to populate your database with development data. This includes all of the original language data as well as English glosses.
```

**Comment by arrocke** [comment]
These suggestions are all great! If you would open a PR with those changes, that will help future contributors
