### ISSUE TITLE
explore what is possible with fetch.bible

### ISSUE THREAD

**Issue by arrocke** [arrocke/gloss-translation#154]
We need to answer a few questions to inform our approach towards reference translations:
* How could we use fetch.bible to build a UI to select which reference translation to associate with a language in our site?
* Do we need to store the reference translation data in our database, or can we load it directly from fetch.bible as we need it?
* What support does fetch.bible provide for rendering translations in different languages?

**Comment by arrocke** [comment]
@Pertempto would you be willing to do some research into this to see if we can use this to load reference translations?

**Comment by Pertempto** [comment]
## Research Results

> How could we use fetch.bible to build a UI to select which reference translation to associate with a language in our site?

Do we really want to have a one-to-one pairing of reference translation to language on our site? See my note below [^1] about the lack of whole bible translations. It seems to me it would be better to use a flexible system, where we mix-and-match translations for a language to increase coverage.

I'm imagining we could store a list of translation "priorities" in our DB. Then when a translator is working on a verse, a dropdown selector of translations available for that verse is shown, sorted by priority. By default, the top translation in the available list would be selected. This way we maximize the verses that have a reference translation shown, even if the reference translation is from a "lower" priority translation of the Bible.


> Do we need to store the reference translation data in our database, or can we load it directly from fetch.bible as we need it?

Ideally, I don't think we would need to store the data in our database.  They have a [TypeScript client](https://fetch.bible/access/client/) that allows you to fetch what you need when you need it. I think it would be a good match for our project. There are also [auto-generated docs](https://fetch.bible/access/client/api/classes/client.BibleClient.html). I would need to do some experiments with the client to see how easy it is to use.

The one drawback is that if you want the data in [USX format](https://fetch.bible/access/client/api/classes/book.BibleBookUsx.html), you have to fetch it a whole book at a time. Then we would need to do additional processing to parse the USX and find the chapter/verse we need. In the USX format, it MIGHT make sense to look at caching translation data in our DB.

It looks like they have a better supported [HTML format](https://fetch.bible/access/client/api/classes/book.BibleBookHtml.html), but I'm not sure how well it would integrate with our app. Maybe we could do some additional processing on the HTML to transform to a form we could use.

> What support does fetch.bible provide for rendering translations in different languages?

Not sure what is meant by "support provided for rendering translations", but fetch.bible contains translations for a LONG list of languages: https://fetch.bible/content/languages/

[^1]: Only [11% of the translations](https://fetch.bible/content/stats/) on fetch.bible contain a whole bible. There will be many places where we won't have a reference translation for a particular verse.

**Comment by Pertempto** [comment]
@arrocke I left a general summary above. Please let me know what additional questions I need to answer.

**Comment by arrocke** [comment]
Only remaining question is how the HTML format works, and what options we have to integrate it into our styling. I think we need to have a further conversation with Andrew and Sheldon about how important it is that the reference translation be in the same language. Maybe we have a list of translations associated with each language, but the user can still select a different translation to use as the reference.

**Comment by Pertempto** [comment]
Ok, I'll create a branch and try experimenting with getting HTML

**Comment by Pertempto** [comment]
Here is some example HTML from the WEB translation:

```
            <div class="fb-chapter" data-c="1"><h3 data-c="1">1</h3><p class="fb-p"><sup data-v="1:1">1</sup>In the beginning, God<span class="fb-note">*<span><span class="fb-fr">1:1 </span><span class="fb-ft">The Hebrew word rendered “God” is “אֱלֹהִ֑ים” (Elohim).</span></span></span> created the heavens and the earth. </p></div>
            <p class="fb-attribution">
                <a href="https://ebible.org/Scriptures/details.php?id=eng-web" target="_blank">public domain</a>
                (<a href="https://ebible.org/Scriptures/details.php?id=eng-web" target="_blank">Public domain</a>)
            </p>
```


With the `{attribute: false}` option set:
```
<div class="fb-chapter" data-c="1"><h3 data-c="1">1</h3><p class="fb-p"><sup data-v="1:1">1</sup>In the beginning, God<span class="fb-note">*<span><span class="fb-fr">1:1 </span><span class="fb-ft">The Hebrew word rendered “God” is “אֱלֹהִ֑ים” (Elohim).</span></span></span> created the heavens and the earth. </p></div>
```

**Comment by Pertempto** [comment]
It looks like the auto-generated docs might be out of date. Looking at the type definitions for the library, it appears we can try to retrieve html, usx, usfm, and txt formats.

![image](https://github.com/arrocke/gloss-translation/assets/17209828/6f07ff38-a892-438d-9f57-b2966663db8b)

**Comment by Pertempto** [comment]
Using `book.get_verse(1, 1, {attribute: false, verse_nums: false, headings: false, notes: false})`, I can get the plain text:

```
In the beginning, God created the heavens and the earth. 
```

It seems to me this is the path we should pursue!

**Comment by arrocke** [comment]
What does plain text look like for something like Urdu? Also, is the html format meant for things like verse number and footnotes, and _not_ for differences in languages?

**Comment by Pertempto** [comment]
There are three translations in Urdu. The [first one](https://ebible.org/Scriptures/details.php?id=urdgvr) is using a Roman script. The [second](https://ebible.org/Scriptures/details.php?id=urdgvh) and [third](https://ebible.org/Scriptures/details.php?id=urdirv) seem to be using a Hindi script, instead of the normal Urdu writing system.

```
Ibtidā meṅ Allāh ne āsmān aur zamīn ko banāyā. 
```
```
ख़ुदा ने सबसे पहले ज़मीन — ओ — आसमान को पैदा किया।
```
```
इब्तिदा में अल्लाह ने आसमान और ज़मीन को बनाया। 
```


I did find an [Urdu bible](https://ebible.org/Scriptures/details.php?id=urdgvu) in Urdu script on ebible, but it doesn't seem to be included in `fetch.bible` yet.

**Comment by Pertempto** [comment]
What do you mean
> not for differences in languages?

The different formats are just different ways to render the same data, as far as I understand.

For example, I can get verse numbers and footnotes in the `text` format:

`book.get_verse(1, 1, {attribute: false, verse_nums: true, headings: false, notes: true})`
```
[1:1] In the beginning, God[^a] created the heavens and the earth. 



[^a]: 1:1 The Hebrew word rendered “God” is “אֱלֹהִ֑ים” (Elohim).
```

**Comment by Pertempto** [comment]
Interestingly, there is a ["Sanskrit Bible (NT) in Urdu script"](https://ebible.org/Scriptures/details.php?id=sanurd), which IS part of the fetch.bible data.
```
اِبْراہِیمَح سَنْتانو دایُودْ تَسْیَ سَنْتانو یِیشُکھْرِیشْٹَسْتَسْیَ پُورْوَّپُرُشَوَںشَشْرینِی۔
```

**Comment by arrocke** [comment]
> The different formats are just different ways to render the same data, as far as I understand.

What I'm trying to confirm is whether we can use the text format, or whether the HTML is necessary for handling differences in fonts, language direction, anything else like that. If it's just used for adding footnotes, verse numbers, etc, then we can just use the text. From what you are showing me. The text should work for most or all languages.

I'm going to ask a few clarifying questions of Andrew and Sheldon, but I think we should proceed with a plan to use fetch.bible to provide reference translations.

**Comment by Pertempto** [comment]
Yeah I think the html is just for easy rendering of the text, using their CSS file

**Comment by Pertempto** [comment]
The text format should contain all we need. It's up to us to use a font that supports all the Unicode characters required. It might make sense to use different fonts for different languages, if some fonts don't have all the characters we need

**Comment by arrocke** [comment]
Alright, I think we have what we need for this. I'll roll this into the epic
