### ISSUE TITLE
bash prompter not visible

### ISSUE THREAD

**Issue by ilearner777** [arrocke/gloss-translation#157]
**Describe the bug**
Entered bash command: `nx prisma db migrate reset.` The command required a response from user. However the prompter was not visible, so it never completed.

**To Reproduce**

1. Open bash terminal
2. Enter command: `nx prisma db migrate reset.`
3. Nothing is visible and just sits there.
4. After 31 minutes I entered `ctrl-c` to kill the program. When the program terminated I then saw the prompter. `Are you sure you want to reset your database? All data will be lost. ...`
5. I then ran again and just enter 'Y' without seeing the prompter question.
6. The program then completed successfully

**Expected behaviour**
Expected to see the prompter question.

**Environment (please complete the following information):**

- Laptop
- WIndows 11

**Additional context**
Let me know if I need to change something to make the prompter question visible.

**Comment by arrocke** [comment]
Yeah, this is a limitation of our build system `nx`. It swallows stdin. It's not ideal, but for now it's got this workaround you found.
