### ISSUE TITLE
nx seed db fails

### ISSUE THREAD

**Issue by ilearner777** [arrocke/gloss-translation#158]
**Describe the bug**
Get `Cannot find module './client' or its corresponding type declarations.` error when executing `nx seed db` command.

**To Reproduce**

1. open bash terminal
2. enter command: `nx seed db`
3. Get error message described above and then aborts.

**Expected behavior**
Expected to run successfully and populate local database.

**Environment (please complete the following information):**
- Laptop
- Windows 11

**Additional context**
Checked contents of file `packages/db/src/seed.ts` and see that there is a problem with line 3
``` 
import { PrismaClient } from './client';
```
looks like `client.ts` file is missing in dir: `packages/db/src`.
Please advise how to set up my Prisma Client.

However, I was able to populate thedatabase using alternate command:
```
pg_restore -Fc --format=custom --dbname=<DATABASE_URL> seed.dump
```

**Comment by arrocke** [comment]
Oh, good catch. We had to move the client to the default location for a different issue. I fixed this in 8facaecfd01d61d9c0a301894af9fe72dd7dd46d
