### ISSUE TITLE
Prisma schema path incorrect in package.json

### ISSUE THREAD

**Issue by ilearner777** [arrocke/gloss-translation#159]
**Describe the bug**
file `./package.json` line 90 reads:
```
"schema": "packages/api/prisma/schema.prisma"
```
however, this file is actually located here: 
```
packages/db/src/schema.prisma
```

**To Reproduce**
1. Open file `./package.json`
2. Observe line 90
3. Check for location of file `schema.prisma` in project directory.

**Expected behavior**
Expected to find file in directory specified in `package.json` file

**Environment (please complete the following information):**
- Device: Laptop
- OS: Windows 11

**Additional context**
Should this be corrected?
Are there any implications in it being incorrect?

**Comment by arrocke** [comment]
This just affects the prisma studio. I just pushed up a fix in b720b36
