### ISSUE TITLE
Starting api server fails

### ISSUE THREAD

**Issue by ilearner777** [arrocke/gloss-translation#160]
**Describe the bug**
Executed failed for bash command: `nx server api`

**To Reproduce**

1. Complete instructions in `contributing.md` and `db.md`
2. Open bash and enter command `nx server api`

**Expected behavior**
Expected api server to start at: `localhost:4300`

**Environment (please complete the following information):**
- Laptop
- Window 11

**Additional context**
Below is the output in bash:
```
$ nx serve api

> nx run api:serve:development

node:events:492
      throw er; // Unhandled 'error' event
      ^
Error: spawn C:\Program Files\nodejs\node.exe ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn C:\\Program Files\\nodejs\\node.exe',
  path: 'C:\\Program Files\\nodejs\\node.exe',
  spawnargs: [
    'C:\\Users\\ilear\\Documents\\GitHub\\gloss-translation\\node_modules\\next\\dist\\bin\\next',      
    'dev',
    '--port=4300',
    ''
  ]
}
Node.js v18.17.1

 ——————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Running target serve for project api failed

   Failed tasks:

   - api:serve:development

   Hint: run the command with --verbose for more details.
```

**Comment by arrocke** [comment]
Our build system is trying to spawn a nextjs dev server as a new process and can't find the executable. Is there a file at node_modules/next/dist/bin/next in your local repo?

**Comment by Pertempto** [comment]
> Our build system is trying to spawn a nextjs dev server as a new process and can't find the executable. Is there a file at node_modules/next/dist/bin/next in your local repo?

Yes
<img width="554" alt="image" src="https://github.com/arrocke/gloss-translation/assets/17209828/2b79aee9-a067-409a-a7e9-30b1174aea55">

**Comment by ilearner777** [comment]
I checked my project and Yes, that file does exist.

However, today, in the Nx Console I ran: `api/build/development` followed by `api/serve/development`
Both executed successfully and after that my API executed successfully.

I don't know if the above made any difference. So don't know why it didn't work before and why it works now.

**Comment by arrocke** [comment]
Strange. Usually, I just run `nx serve api` in my terminal and it just works

**Comment by ilearner777** [comment]
When I run: `nx serve api` it works as well. Don't know why it didn't work before but works now.
Nevertheless, you may close this issue as resolved.
