### ISSUE TITLE
lexicon data structure

### ISSUE THREAD

**Issue by arrocke** [arrocke/gloss-translation#162]
* We need a new table that contains lexicon data for each lemma
* Primary key will combine the lemma id and the lexicon code (`bdb`, `lsj`, `strongs`)
* Table needs a string field with the markdown entry.

**Comment by Pertempto** [comment]
So there would be 3 fields?
- `lemmaId`
- `lexiconCode`
- `content`

**Comment by arrocke** [comment]
I think that's right, yes

**Comment by Pertempto** [comment]
I'll try this one. It should be a good way to get my feet wet with modifying the Prisma schema
