### ISSUE TITLE
process to import BDB data

### ISSUE THREAD

**Issue by arrocke** [arrocke/gloss-translation#163]
* Use the `BdbMedDef` field from [this data source](https://raw.githubusercontent.com/STEPBible/step/master/step-core-data/src/main/resources/com/tyndalehouse/step/core/data/create/lexicon/lexicon_hebrew.txt) to generate lexicon entries.
* We need a script to process this data and update the database so it can be repeated.
* The bdb definition will need to be converted to markdown

**Comment by Pertempto** [comment]
> We need a script to process this data and update the database so it can be repeated.

What were you imagining this would look like/entail?

**Comment by arrocke** [comment]
We could create a script like the seed script so that you could run it with the command `nx run db:import-bdb`. That command would replace all BDB resource entries with data from the seed file. We'll also need to figure out the structure of the resource entry so we can come up with a standard way of converting it to its markdown equivalent.

**Comment by Pertempto** [comment]
I've got some basic code that converts that file into a JSON object.

I then ran a counter for the `<>` tags. Here are the results

```
{
  '<BR>': 6566,
  '<i>': 2397,
  '<br>': 36419,
  '<ref="Pro.30.1-33">': 1,
  '<ref="1Ch.8.6">': 4,
  '<ref="Amo.1.5">': 1,
  '<ref="Hos.10.8">': 1,
  '<ref="2Sa.11.3">': 1,
  '<ref="Psa.22.1">': 1,
  '<ref="Deu.3.11">': 1,
  '<ref="Ezk.40.5">': 1,
  '<ref="Jdg.12.5">': 2,
  '<ref="1Ki.11.26">': 2,
  '<ref="Rut.1.1">': 2,
  '<ref="1Sa.1.1">': 2,
  '<ref="1Sa.17.12">': 2,
  '<ref="2Sa.24.16">': 1,
  '<ref="2Sa.24.18">': 1,
  '<ref="Psa.84.6">': 1,
  '<ref="Psa.8.1;">': 1,
  '<ref="Gen.25.3">': 1,
  '<ref="1Ch.1.32">': 1,
  '<ref="Pro.30.31">': 1,
  '<ref="Jos.15.25">': 1,
  '<ref="Psa.39.1;">': 2,
  '<ref="Psa.56.1">': 1,
  '<ref="Heb.11.37">': 1,
  '<ref="Psa.7.1">': 5,
  '<ref="Jer.36.14">': 1,
  '<ref="Zep.1.1">': 1,
  '<ref="1Sa.17.6">': 1,
  '<ref="Dan.11.43">': 1,
  '<ref="Jer.46.9">': 1,
  '<ref="Psa.53.1">': 1,
  '<ref="Psa.81.1">': 1,
  '<ref="Neh.5.11">': 1,
  '<ref="Pro.30.31;">': 1,
  '<ref="Psa.5.1">': 1,
  '<ref="Gen.10.22;">': 5,
  '<ref="1Ch.1.17">': 5,
  '<ref="1Sa.13.21">': 6,
  '<ref="Lev.13.1--14:57">': 1,
  '<ref="Lev.13.47-52">': 1,
  '<ref="Lev.14.34-53">': 1,
  '<ref="Ps.45.1">': 1,
  '<ref="Psa.60.1">': 1,
  '<ref="Psa.80.1">': 1,
  '<ref="Dan.7.5">': 1,
  '<ref="Mat.8.30-32">': 1,
  '<ref="Pro.23.7">': 1,
  '<ref="Num.24.17">': 1,
  '<ref="Ecc.10.17">': 1,
  '<B>': 1,
  '<->': 1
}
```

**Comment by Pertempto** [comment]
- `br` - We should be able to just convert these to the markdown double-newline, so it shows up as a newline in the final output
- `BR` - Not sure if there is any difference between this and `br`
- `i` - I think these are some kind of link. They are of the form of `<i>ta.a.re.a</i>`. I'm not sure how we want to handle them
- `ref=` - Do we want to handle these? It appears that the reference format isn't even consistent ('Psa' vs "Ps')
- `B` - I'm guessing that's just a typo of `BR`
- `-`- We can ignore this one, it's from the definition
    > Verbal vav: joined to verb with no intervening prefix (usually conversive)  (future<->past)

**Comment by Pertempto** [comment]
@arrocke Any thoughts?

**Comment by arrocke** [comment]
This is great! Two thoughts:
- `i` - These look like transliteration from hebrew and aramaic. Let's convert these to italic text for now
- `ref` - for now, let's strip these tags out and leave the text of the reference. Later we can add something more fancy like a popover with the verse text

**Comment by Pertempto** [comment]
Our lemma IDs are all of the simple form `H0001`, but the lexicon data sometimes contains lemma IDs like `H0001G`, `H0001H`, and `H0001I`. How do you want to handle these situations? Should I just concatenate those definitions with new lines for now?

**Comment by Pertempto** [comment]
I could also stick a horizontal rule between them.

**Comment by arrocke** [comment]
Oh good catch. Those lemma IDs are for lemmas that were identified after Mr. Strong finished his concordance. Ideally, we would update the words in our biblical dataset to point to those lemmas. I'll add a story later today to address that. For now can we import them as unique lemmas even though no words are pointing to them?

**Comment by Pertempto** [comment]
Not unless we remove the foreign key restraint

**Comment by arrocke** [comment]
The Lemma table has no foreign keys. What prevents us from having extra lemmas that aren't yet connected to any words?

**Comment by Pertempto** [comment]
LemmaResource has the foreign key

Currently I'm just inserting LemmaResource items, but sure I can also insert Lemma for the missing ones
