### ISSUE TITLE
process to import LSJ data

### ISSUE THREAD

**Issue by arrocke** [arrocke/gloss-translation#164]
* Use the `FLsjDefs` field from [this data source](https://raw.githubusercontent.com/STEPBible/step/master/step-core-data/src/main/resources/com/tyndalehouse/step/core/data/create/lexicon/lexicon_greek.txt) to generate lexicon entries.
* We need a script to process this data and update the database so it can be repeated.
* The lsj definition will need to be converted to markdown

**Comment by Pertempto** [comment]
It will be SUPER easy to take what I did in #241 and create a equivalent greek import script.

**Comment by Pertempto** [comment]
At what point will we be able to actually display the lexicon entries in the frontend?

**Comment by arrocke** [comment]
I haven't written that ticket yet. I'll do that this week
