### ISSUE TITLE
API routes to load lexicon data

### ISSUE THREAD

**Issue by arrocke** [arrocke/gloss-translation#166]
* Add a new route `GET /lemma/:lemmaId/resources`
* This route is going to return all lexicon entries for a certain lemma
* Return data in the following shape:
```
{
  data: {
    resource: string
    entry: string
  }[]
}
```

**Comment by Pertempto** [comment]
Should it now be `GET /lemma/:lemmaId/resources` and 

```
{
  data: {
    resource: string
    entry: string
  }[]
}
```

**Comment by arrocke** [comment]
Good call. I updated the description
