### ISSUE TITLE
save reference when returning to translation view

### ISSUE THREAD

**Issue by LouKehler** [arrocke/gloss-translation#167]
**Describe the bug**
The reference is forgotten when switching tasks. The language of translation is remembered but the page goes back to Genesis 1:1.

**To Reproduce**

1. Navigate to Gen 1:2 or any reference other than Gen 1:1
2. Click on 'Languages'
3. Click on 'Translate'
4. Goes back to Gen 1:1

**Expected behavior**
I would expect it to return to the last reference that was being worked on or viewed.

**Screenshots**
Not necessary.

**Environment (please complete the following information):**

- Device: Desktop
- OS: Windows 11
- Browser: Edge
- Version: ???

**Additional context**

**Comment by arrocke** [comment]
This is a good idea!. I'll put it in the queue to be worked on. I think we can solve this by putting the last reference in local storage

**Comment by Pertempto** [comment]
I'll work on this once I get caught up with code review.
