### ISSUE TITLE
Gloss font

### ISSUE THREAD

**Issue by LouKehler** [arrocke/gloss-translation#168]
**Is your feature request related to a problem? Please describe.**
When I work in Urdu as a gloss language the text is difficult to read.

**Describe the solution you'd like**
I would like to see the ability to display the gloss text in another font such as Scheherazade that has been tweaked for Urdu or better yet, an Urdu Nastaliq font such as Mehr.

**Describe alternatives you've considered**
In the Languages tab for each language any admin would have the ability to upload a font and choose to use that font for displaying the language.

**Additional context**
none.

**Comment by arrocke** [comment]
@LouKehler Have you ever used the [Noto](https://fonts.google.com/noto/specimen/Noto+Nastaliq+Urdu) font for Urdu? Noto seems like the a great set of fonts that supports nearly every language and script in the world. I'm wondering how far we could get by using variants of this font for different languages. But I have no idea if it's any good for Urdu

**Comment by LouKehler** [comment]
Yes, Noto Nastaliq works fine and includes support for minority languages. It isn't as pretty as some but works. I know the designer, Kamal, who works for Monotype. He also designed the font "Noori Nastaliq MT" that I use in the BART Bible app for Urdu. I have the only five licenses for that font that exist. I bought them directly from Monotype.

**Comment by arrocke** [comment]
Ok cool. One of the challenges we'll have to design for is how load all of these fonts on demand. I'm going to put this in the queue to be worked on

**Comment by Pertempto** [comment]
@arrocke, what exactly are you wanting to be added in this issue? Does this just involve changing the gloss font, or implementing some kind of font selector?

**Comment by arrocke** [comment]
Ultimately we need to be able to select the appropriate font for any language. If we can find a way to do that automatically, great. Otherwise we need the option for language admins to configure the font.

**Comment by LouKehler** [comment]
I don't see how you could predict this automatically. Many non-European gloss languages would potentially require a font. Since you create a new language through the menus it would be expected that the font for that language would be chosen from a list of possibilities.

**Comment by arrocke** [comment]
The only idea I had to do it automatically was to tie each language code to a set of font families in advance so that when a language sets their language code, we know what font to use. But perhaps it is better to just let the language admin choose.

**Comment by Pertempto** [comment]
@arrocke What if we start with the simple strategy, allowing admins to configure the font, and come back to the automatic association idea in the future.

If we did implement the automatic association, I think it would just create a better default value for the font selector when they setup a new language. The admin should still be allowed manually override if they need to.

**Comment by LouKehler** [comment]
I think it would be sufficient for admins to configure the font.

**Comment by arrocke** [comment]
If we are ok with what is available for free with Google Fonts and want to allow language admins to pick from any of their options, we can use the [Developer API](https://developers.google.com/fonts/docs/developer_api) to get the list of options for the font picker. We might want to find a way to narrow down the options so there aren't so many to sort through.

**Comment by Pertempto** [comment]
Will you setup an API key for the project?

**Comment by arrocke** [comment]
Yep, I'll try to do that this week
