### ISSUE TITLE
User interface not being updated

### ISSUE THREAD

**Issue by LouKehler** [arrocke/gloss-translation#169]
**Describe the bug**
User interface not being updated.

**To Reproduce**

1. Select 'Profile'
2. Change name to a new name
3. Select 'Users"
4. User is still displayed with the previous name

**Expected behavior**
I expect my profile name to be updated.

**Screenshots**

**Environment (please complete the following information):**

- Device: Desktop
- OS: Windows 11
- Browser: Edge
- Version: 

**Additional context**
none

**Comment by arrocke** [comment]
I'm going to run through the app for this issue. Seems like we've missed this in a few places
