### ISSUE TITLE
configure default reference translations for a language

### ISSUE THREAD

**Issue by arrocke** [arrocke/gloss-translation#171]
A language admin should be able to set which translations from fetch.bible the language will use. It should provide them an autocomplete from the fetch.bible list to pick the translations. The user also needs to be informed how complete the translation is.

**Comment by Pertempto** [comment]
This selector would be on the manage language page? Above the import glosses button?

It sounds like you want to support multi-select. In the situation that multiple translations have available data for a given verse, what determines priority between those translations?

**Comment by arrocke** [comment]
I can do some work in figma for this. I think we are going to need to allow them to reorder the translations to determine the priority. Maybe the first pass, should just support a single language and we can add priorities with multiple translations later?

**Comment by Pertempto** [comment]
This would be pretty similar code changes to #168, correct? I think I can implement it.

The work you were doing in Figma was for supporting multiple translations, right? I should be good to go to implement the first pass with just a single translation per language?

I'll implement the translations field on the language entity in Prisma as a string array, so that we can easily support multiple translations per language in the future.

**Comment by arrocke** [comment]
I think we could use the auto complete component with multiselect for this like we do for language roles. Maybe there is a better UI, but that's a pattern we already have. Later we can build a UI to reorder them for priority.

**Comment by Pertempto** [comment]
The scope for this issue is one translation per language or multiple per language? I was suggesting saving the multiple for a different issue, but maybe that is silly

**Comment by arrocke** [comment]
I think we could use the auto complete component with multiselect for this like we do for language roles. Maybe there is a better UI, but that's a pattern we already have

**Comment by arrocke** [comment]
I'd just go for the multiple translations per language and leave the sorting for a different story. I don't think it changes the effort all that much.
