### ISSUE TITLE
show translation from fetch.bible for the current verse

### ISSUE THREAD

**Issue by arrocke** [arrocke/gloss-translation#172]
If we know the preferred translations for the language, we can show the text from the first translation that has the verse. If no translation has the verse, we should notify the user that a translation doesn't exist.

**Comment by Pertempto** [comment]
Do we have a design for how this should look?

**Comment by arrocke** [comment]
This is what I mocked up a while ago

<img width="717" alt="Screen Shot 2023-10-09 at 10 15 06 PM" src="https://github.com/arrocke/gloss-translation/assets/11968925/ab60baa5-1257-443f-bbbd-00b97fa4fa78">

**Comment by Pertempto** [comment]
How important do you think it is to display the "1:2" at the beginning of the translation? It makes it look nicer, but it will require us to have a new format string for every language. It seems redundant when the full reference is literally right above it.

**Comment by arrocke** [comment]
I'm good with not showing that. We could show the translation version instead if you want

**Comment by arrocke** [comment]
@Pertempto We'll want to use the new language text direction setting I added in #231 in the reference translation
