### ISSUE TITLE
How to logon as ADMIN in web app

### ISSUE THREAD

**Issue by ilearner777** [arrocke/gloss-translation#173]
**Describe the bug**
I have installed prostgres database and have seeded the db, but I don't have ability to login as ADMIN to test or use app.

**To Reproduce**
1. Install local env as per `contributing.md` and `db.md`.
2. Try to login. Not able to log into local web app as don't have valid email and pwd.

**Expected behavior**
Expected documentation to explain how to create a test ADMIN id.

**Environment (please complete the following information):**
- Laptop
- Windows 11

**Additional context**
Should this be added to `db.md`?

**Comment by arrocke** [comment]
Good catch. This is missing from the docs. The user and password should be `devyn61@ethereal.email` and `asdf1234`. We can add to the end of the Local Development section
