### ISSUE TITLE
Errors in file lucai.d.ts

### ISSUE THREAD

**Issue by ilearner777** [arrocke/gloss-translation#174]
**Describe the bug**
Opened file: `packages/api/lucia.d.ts` and IDE highlighted 2 errors:
1. line 1:  `/// <reference types="lucia" />` Error: `Cannot find type definition file for 'lucia'.ts(2688)`
2. line 6:  ` emailStatus?: import('@translation/db').EmailStatus;` Error: `Cannot find module '@translation/db' or its corresponding type declarations.ts(2307)`

**To Reproduce**
1. Open file:  `packages/api/lucia.d.ts
2. Observe error messages 

**Expected behavior**
Did not expect to find any errors in this file.

**Environment (please complete the following information):**
- Laptop
- OS: Window 11

**Comment by arrocke** [comment]
I noticed this while working on a different branch. Should be fixed in #176
