### ISSUE TITLE
Error in file packages/api/tsconfig.json

### ISSUE THREAD

**Issue by ilearner777** [arrocke/gloss-translation#175]
**Describe the bug**
Opened file `packages/api/tsconfig.json` and IDE highlighted 1 error:
line 1: `{` 
```
Error: File 'gloss-translation/packages/nx-plugin/src/index.ts' not found.
  The file is in the program because:
    Root file specified for compilation ts
```
**To Reproduce**
1. Open file.
2. Observe error message

**Expected behavior**
Did not expect to see any errors in this file.

**Environment (please complete the following information):**
- Laptop
- OS: Windows 11

**Comment by arrocke** [comment]
There was a line in the base tsconfig that was causing this that I've removed. Fixed in 43b3425
