### ISSUE TITLE
Project organization

### ISSUE THREAD

**Issue by arrocke** [arrocke/gloss-translation#178]
I'm really used to using epics and stories in an agile way. I'm not sure that is entirely useful for an open source project without sprints. I'm considering removing epics as an issue type, and treating every feature as a normal issue. Whoever is working on the issue can of course open multiple PRs to make reviewing easier, but I don't have to spell out the order in which each task has to happen in order to complete the feature. Instead I think fewer issues that describe everything that has to happen before the issue can be closed, might work better.

**Comment by arrocke** [comment]
@Pertempto What do you think of this approach?

**Comment by Pertempto** [comment]
I agree that working in an agile way doesn't make sense, but epics still work as a good way to organize our issues and show how a series of issues build upon each other. If you're suggesting that we create big issues that will conquer new feature sets, I don't support that approach at all. Keeping the issues small, in bite-size chunks, makes a BIG difference in keeping a project moving smoothly (at least in my experience, the caveat being I don't have as much experience as you).

I'm fine with coming up with a new approach for organizing our issues, but at the same time I'm not sure I totally understand what's wrong with our current structure. Don't think of the epics as a sprint planning tool, think of them as a way to organize issues.


I do agree that using epic issues is kind of strange. They get all mixed up with our normal issues. In Gitlab, which is what I'm used to working in, milestones, epics, iterations, and issues are all separate entities. GitHub doesn't seem to have all those built-in, but it does have milestones. Maybe we could look at using those more? 

Overall, I'm saying that having some kind of way to organize all the issues that go into making a new feature set is pretty important in my experience. No matter what name you use for that, whether it be "milestone", "epic", or something else, I think we should include it in our organization strategy.

**Comment by arrocke** [comment]
I think you convinced me to stay the course for now. I want to treat milestones as groups of epics, so right now we are working on the beta milestone.
