### ISSUE TITLE
Zoom on page not working normally

### ISSUE THREAD

**Issue by BethedenMinistries** [arrocke/gloss-translation#180]
The usual ways to zoom into the page don't work. So ctrl + doesn't do anything. For a while I thought that it was impossible to zoom in at all, but I was able to go into the menu on Chrome and do it manually.

**Comment by arrocke** [comment]
Are you on Windows or Mac? On my mac the keyboard shortcut for zooming on chrome is Cmd +, and it works for me.

**Comment by Pertempto** [comment]
Hmmm, it works for me on Windows too

**Comment by BethedenMinistries** [comment]
I'm on Chrome on Windows 11. I've restarted many times since then, updated Chrome, and it still glitched. Then all of a sudden it worked. So I'm not sure what's going on, but now it works and I can't make it reproduce the glitch.

**Comment by arrocke** [comment]
Ok, I'm going to close this for now then.
