### ISSUE TITLE
Use Enter key to save glosses

### ISSUE THREAD

**Issue by BethedenMinistries** [arrocke/gloss-translation#182]
The Enter key should also save glosses (along with Tab). That avoids data loss, since many people are used to Enter already.

**Comment by arrocke** [comment]
@BethedenMinistries I think this is the behavior already. Can you elaborate more on what the problem is and how this issue is different from #183 ?

**Comment by BethedenMinistries** [comment]
I think the confusion is that when I hit Enter it doesn't advance to the next gloss. That's what I'd like to happen.
