### ISSUE TITLE
Next Unapproved Verse & Approve All Buttons

### ISSUE THREAD

**Issue by BethedenMinistries** [arrocke/gloss-translation#190]
Sheldon's app has two buttons/shortcuts that are still lacking: Approve All and Next Unapproved Verse.
We definitely need this functionality before people switch over.

**Comment by arrocke** [comment]
@BethedenMinistries Can we get away with keyboard shortcuts, or do we need actual buttons?

**Comment by BethedenMinistries** [comment]
I guess, but there are probably users who would appreciate the buttons. Is there something more complicated with adding buttons? It would only be for the people interlinearizing.

**Comment by arrocke** [comment]
It's only more complicated because we need to design the UI to include them. A keyboard shortcut doesn't need that. I can work on that

**Comment by BethedenMinistries** [comment]
I see. So do you mean that a graphic designer would need to help with the design decisions for the UI before making the buttons to match the design language?

**Comment by arrocke** [comment]
I just meant that I want to give some thought about where it makes sense for those buttons to go and how we should present them. It would be nice to have a UX designer for these kinds of questions, but I for now we can make do with my experience.

**Comment by arrocke** [comment]
This was broken out into separate issues for developers to work on:
* #357 
* #356
