### ISSUE TITLE
partial data breaks import

### ISSUE THREAD

**Issue by arrocke** [arrocke/gloss-translation#192]
Partial data from the current site breaks the import logic. We'll need to investigate and account for partial data.

**Comment by Pertempto** [comment]
Partial data in what way?

**Comment by arrocke** [comment]
It seemed like that languages that haven't glossed everything failed with errors. I'm still investigating

**Comment by arrocke** [comment]
Turns out the issue was just that the lambda didn't have enough memory. I fixed that and now it appears to work fine
