### ISSUE TITLE
Ability to make a gloss unconfirmed

### ISSUE THREAD

**Issue by BethedenMinistries** [arrocke/gloss-translation#203]
Sometimes someone will accidentally or purposefully confirm a gloss as correct and then change their mind and want to leave it unconfirmed so that they can come back to it later after more research, etc. It would be nice to be able to use a shortcut key to unconfirm a gloss that has already been confirmed.

**Comment by arrocke** [comment]
@BethedenMinistries If the user has typed in a gloss, do we want to revert to the prefilled gloss from Google Translate, or leave what the user typed, but mark it as unconfirmed?

**Comment by BethedenMinistries** [comment]
We want to leave what the user typed, but mark it as unconfirmed.

**Comment by arrocke** [comment]
[Design](https://www.figma.com/file/GYKTJWl1otgwpmA9ZLLthE/Gloss-Translation-App?type=design&node-id=1218-701&mode=design&t=4tqE0ADsS4nGJ9XJ-0) for this is complete. I want to change the autocomplete input first before we introduce the concept of approval

## acceptance criteria
* A gloss needs a status field, that will take one of two values `APPROVED` and `UNAPPROVED`
* A gloss that is approved will appear with a green border, and a green checkmark and the text `Approved` under the gloss input
* Hitting enter in the input or making a selection from the dropdown menu will mark the gloss as approved
* Hitting escape in the input will mark the gloss as unapproved

<img width="606" alt="Screen Shot 2023-09-27 at 9 41 56 PM" src="https://github.com/arrocke/gloss-translation/assets/11968925/1022a110-5434-4e2b-85c9-77dafb863ef1">
