### ISSUE TITLE
glossing language dropdown visual glitch

### ISSUE THREAD

**Issue by Pertempto** [arrocke/gloss-translation#216]
**Describe the bug**
The glossing language dropdown has incorrect background and/or z index

**To Reproduce**
1. Create multiple languages
2. Go to the translation view
3. Click on the glossing language dropdown

**Expected behavior**
The dropdown should be shown above the translation content

**Screenshots**
<img width="200" alt="image" src="https://github.com/arrocke/gloss-translation/assets/17209828/0d14fd10-f09f-4963-b335-8af73eaeba40">

**Environment (please complete the following information):**

- Device: Laptop
- OS: Windows 11
- Browser: Vivaldi (Chromium-based)

**Comment by arrocke** [comment]
This should be fixed in 36145ab
