### ISSUE TITLE
configure language direction

### ISSUE THREAD

**Issue by arrocke** [arrocke/gloss-translation#223]
We need to configure the language direction so that we can modify the UI accordingly when that language is used. This impacts the gloss selector and reference translation at this point and probably other things eventually.

**Comment by Pertempto** [comment]
Is it really an alignment issue? I think it would look MUCH better to just make the input take up the full width of the parent, and then it wouldn't matter which way it was aligned. 

![image](https://github.com/arrocke/gloss-translation/assets/17209828/1637046b-7ebd-4dfc-818e-81494ac0dc77)

I'm also seeing a lot of issues with autocomplete inputs clipping their contents.
<img width="300" alt="image" src="https://github.com/arrocke/gloss-translation/assets/17209828/4573a1df-f4c4-4462-bbb1-ae1153ca2bc3">

**Comment by arrocke** [comment]
It also affects how the cursor works inside the text input. We are changing the alignment to match the ancient language, but often times the cursor still needs to work in the opposite direction because the glossing language is different.

On the stretching issue, I haven't found a good way with CSS to force the selector to be full width when the gloss text is shorter, but also force the width to be wider when the gloss text is the longest.

**Comment by Pertempto** [comment]
Ok that makes sense. As you mentioned about the stretching issue, I think I tried to get it to work before and couldn't find a good solution either. If we can ever figure it out someday, I think it'd look much better.

**Comment by arrocke** [comment]
I tried something in the gloss alignment PR that I just merged to address the stretching and it seems to work pretty well. I'm looking at the ancient language, the reference gloss, and translated gloss widths and picking the longest.
