### ISSUE TITLE
Call for volunteers video

### ISSUE THREAD

**Issue by arrocke** [arrocke/gloss-translation#238]
Andrew wants to make a video calling for volunteers for this project. What should that video include?

**Comment by arrocke** [comment]
@Pertempto Any suggestions here?

I'm thinking a few things:
* Basic tech - typescript, nextjs, react
* Link to repo
* Roles needed - developers, devops, UX designers

**Comment by Pertempto** [comment]
I would maybe include Prisma in the basic tech. It has been a learning curve for me.

**Comment by arrocke** [comment]
I'm thinking we just say postgresql since that's the underlying database technology
