### ISSUE TITLE
Branding

### ISSUE THREAD

**Issue by arrocke** [arrocke/gloss-translation#240]
I'm thinking we should lean into the Aleph with Beth brand. That would mean a deep blue as the primary color, maybe a yellow as an accent color.

Here is an option. We can shade these to be less bright in some cases.
Primary (buttons, links, focus, etc) - #005A9F
Accent (region backgrounds) - #F6AE2D
Success - #7EA172
Error - #D33F49

**Comment by Pertempto** [comment]
I like it! Wouldn't we just call the "interactivity" color our "primary" color?

**Comment by arrocke** [comment]
This is a duplicate of #325
