### ISSUE TITLE
test user interviews

### ISSUE THREAD

**Issue by arrocke** [arrocke/gloss-translation#245]
We've got a handful of users that are going to use the new site to give us feedback. I'd like to do the following:

1. Give them an account and a language to work on
2. Set up an video call where we can watch them start to use the app, listen to their thought process, and see where they get stuck
3. Have them use the app for a bit and translate a few chapters. Gather more feedback at this point

I suspect that we will have some minor changes and new feature ideas from this, as well as some ideas for how we could build tools for onboarding new people.

**Comment by arrocke** [comment]
Interview questions:
* How much have you used of the current app?
* What resources do you use when doing biblical translation?
* What is the most difficult part of deciding how to translate a word or a phrase?
* Is there anything else I should know about what it's like being a translator?

Tasks to observe:
* Select and approve glosses for this verse.

**Comment by Pertempto** [comment]
It's kind of included in point 4, but I would maybe make a point to ask this as well:
- Which parts of the new app do you find unintuitive or hard to use?

I think we should be on the watch for pain points from the get go, and be ready to adjust quickly and aggressively to anything that commonly comes up.

**Comment by arrocke** [comment]
That's part of what I'm going to be doing with observing them using it initially. I want to find out what is confusing for a new user. I'm also going to return to that question after the've used if for a while

**Comment by arrocke** [comment]
Going to close this now since I have a script I'm using for these interviews
