### ISSUE TITLE
Document Dev Import Process

### ISSUE THREAD

**Issue by Pertempto** [arrocke/gloss-translation#246]
**Is your feature request related to a problem? Please describe.**
Add the steps from https://github.com/arrocke/gloss-translation/pull/176 to our docs, so that it is easier to remember how to import glosses locally.

**Describe the solution you'd like**
`docs/import.md` file that describes the steps

**Comment by Pertempto** [comment]
Important notes to mention
1. Docker needs to be running before trying to run `nx run lambda-functions`
2. The `Failed to parse source map` error is normal and can be safely ignored

**Comment by Pertempto** [comment]
@arrocke 

How does this code in the lambda function work? I'm not sure how the `event` system works in the local enviroment.

```js
    const { languageCode, importLanguage, jobId } = JSON.parse(
      event.Records[0].body
    ) as {
      languageCode: string;
      importLanguage: string;
      jobId: string;
    };
```

Somehow my lambda function is getting a `languageCode` of `es`, while my database has the language code of `spa`

```
> nx run lambda-functions:serve

Invoking main.lambdaHandler (nodejs18.x)
Local image is up-to-date
Using local image: public.ecr.aws/lambda/nodejs:18-rapid-x86_64.
Mounting C:\Users\addis\SoftwareProjects\gloss-translation\gloss-translation\dist\packages\lambda-functions as /var/task:ro,delegated, inside runtime container
START RequestId: 0a0c639f-e626-42bd-ab37-722cbe57bdf0 Version: $LATEST
2024-04-22T08:53:28.094Z        0a0c639f-e626-42bd-ab37-722cbe57bdf0    INFO    Import Spanish to es ... start
2024-04-22T08:53:29.947Z        0a0c639f-e626-42bd-ab37-722cbe57bdf0    INFO    Import Spanish to es ... complete
END RequestId: 0a0c639f-e626-42bd-ab37-722cbe57bdf0
REPORT RequestId: 0a0c639f-e626-42bd-ab37-722cbe57bdf0  Init Duration: 0.18 ms  Duration: 2684.33 ms Billed Duration: 2685 ms Memory Size: 500 MB     Max Memory Used: 500 MB
{}
```

**Comment by arrocke** [comment]
There is an event.json file that determines the event sent to the lambda
