### ISSUE TITLE
Local Import Process Broken

### ISSUE THREAD

**Issue by Pertempto** [arrocke/gloss-translation#247]
**Describe the bug**
The import process doesn't run correctly in the lambda function

**To Reproduce**

Run the steps from #176 

1. Comment out the SQS queue code in the post import request. This will allow you to test the lambda locally without SQS.
2. Import the spanish glosses to a language
3. Run `nx serve lambda-functions`
4. When the lambda completes, verify that the import view shows success screen

**Expected behavior**
The import view should show success, the glosses should be imported

**Screenshots**
The import view never updates, the glosses are not imported

**Environment (please complete the following information):**

- Device: Laptop
- OS: Windows 11
- Browser: Vivaldi

**Additional context**
`endDate` is never set by the import job, even though it seems to run succesfully

<img width="606" alt="image" src="https://github.com/arrocke/gloss-translation/assets/17209828/4886b7f0-5172-49b4-81fe-b00731751fd5">

```
$ nx serve lambda-functions

 >  NX   Running target serve for project lambda-functions and 2 tasks it depends on:

 ————————————————————————————————————————————————————————

> nx run lambda-functions:build  [local cache]

chunk (runtime: main) main.js (main) 316 KiB (javascript) 670 bytes (runtime) [entry] [rendered]

WARNING in ../../node_modules/@prisma/client/runtime/library.js
Module Warning (from ../../node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Users\addis\SoftwareProjects\gloss-translation\gloss-translation\node_modules\@prisma\client\runtime\library.js.map' file: Error: ENOENT: no such file or directory, open 'C:\Users\addis\SoftwareProjects\gloss-translation\gloss-translation\node_modules\@prisma\client\runtime\library.js.map'

webpack compiled with 1 warning (18cee9555525b431)

> nx run lambda-functions:serve

Invoking main.lambdaHandler (nodejs18.x)
Local image is up-to-date
Using local image: public.ecr.aws/lambda/nodejs:18-rapid-x86_64.
Mounting C:\Users\addis\SoftwareProjects\gloss-translation\gloss-translation\dist\packages\lambda-functions as /var/task:ro,delegated, inside runtime container
START RequestId: 66fe1c74-efc5-4107-ac9f-3e669d22e85a Version: $LATEST
2023-10-30T08:49:39.148Z        66fe1c74-efc5-4107-ac9f-3e669d22e85a      INFO    Import Spanish to es ... start
2023-10-30T08:50:01.441Z        66fe1c74-efc5-4107-ac9f-3e669d22e85a      INFO    Import Spanish to es ... complete
END RequestId: 66fe1c74-efc5-4107-ac9f-3e669d22e85a
REPORT RequestId: 66fe1c74-efc5-4107-ac9f-3e669d22e85a  Init Duration: 1.09 ms    Duration: 39706.01 ms   Billed Duration: 39707 ms Memory Size: 500 MB     Max Memory Used: 500 MB
{}

 ————————————————————————————————————————————————————————

 >  NX   Successfully ran target serve for project lambda-functions and 2 tasks it depends on

   Nx read the output from the cache instead of running the command for 2 out of 3 tasks.


```

**Comment by Pertempto** [comment]
CC @arrocke

maybe I'm doing something wrong

**Comment by arrocke** [comment]
I suspect that this is due to the `event.json` in the lambda functions project not matching the code of the language in the database. You should be seeing logs for each book of the bible. When I changed the `event.json` to use `spa` it worked just fine
