### ISSUE TITLE
Issue with "nx prisma db migrate reset"

### ISSUE THREAD

**Issue by ilearner777** [arrocke/gloss-translation#254]
**Describe the bug**
In document `db.md`, line 18, it instructs the user to run command `nx primsa db reset`, 
However, when itruns, it waits for confirmation from the user. Unfortunately, the confirmation prompt is not visible. So it appears that the routine never finishes. It does not become visible until the user presses ctrl-c.  

**To Reproduce**

1. In a terminal run `nx prisma db migrate reset`

**Expected behavior**
Expect prompt to appear, or alternatively specify an argument to avoid the confirmation prompt.

**Environment (please complete the following information):**
- Device: Laptop
- OS: Windows 11 Home Edition

**Recommended Solution**
The following change has been tested and resolves the problem.
1. To scaffold the database schema and seed the database with data, in a terminal run:

    ```bash
    nx prisma db migrate reset --force
    ```

**Comment by Pertempto** [comment]
Just type "y" when it appears to hang, and it will run. The prompt doesn't show up for some reason.

We should figure out how to fix that, or document the issue better.

**Comment by arrocke** [comment]
The issue is with how nx pipes output from forked processes: https://github.com/nrwl/nx/issues/8269

I'm fine if we want to update our docs to recommend using the --force flag for resetting, but there will other times with prisma where it is prompting you unknowingly, usually because it wants to reset the database before creating a new migration

**Comment by Pertempto** [comment]
Yeah I'm not a big fan of using `--force` all the time.

**Comment by ilearner777** [comment]
If there isn't consensus on using `--force`, then perhaps we can add the following to our `db.md` document:

NOTE: After issuing this command, there may be a pause after it displays information similar to the following example: 

```text
Prisma schema loaded from packages\db\src\schema.prisma
Datasource "db": PostgreSQL database "gloss-translation", schema "public" at "localhost:5432"
```
 If this occurs, the routine is waiting for user confirmation to authorize the resetting of the database.  Unfortunately, the wording of the confirmation prompt does not appear. To authorize a reset, simply press the `Y` key followed by the `Enter` key to confirm. The routine will then continue to completion.

Let me know if you there is consensus on the above, other wise, feel free to close this issue.

**Comment by arrocke** [comment]
In that issue I linked to, someone made a [custom nx executor](https://gist.github.com/MinskLeo/749311c117996cf88e5594e61a4bb333) that handles interactive commands like prisma. I think we should try that first
