### ISSUE TITLE
Recent change to branch main, cause web app to hang

### ISSUE THREAD

**Issue by ilearner777** [arrocke/gloss-translation#255]
**Describe the bug**
Today I pulled the most recent changes to branch main, When I started the web app, it hung trying to retrieve the glosses for Gen. 1:1

**To Reproduce**

1. Pull code from upstream and sync to local environment
2. Run `npm install`
3. Run `nx prisma db migrate reset --force`
4. Start api app
5. Start web app

**Expected behavior**
Expected web app to display interlinear information for Gen. 1:1

**Screenshots**

Here I get a spinning circle:
![Issue1](https://github.com/arrocke/gloss-translation/assets/141659916/bdd36a48-7e54-461c-91cb-2b837942d335)

API app keeps repeating line: `http://localhost:4300/api/languages/en/verses/01001001/glosses`
![Issue2](https://github.com/arrocke/gloss-translation/assets/141659916/844c7f76-164f-49ba-8f01-1f0599e5aa4a)

**Environment (please complete the following information):**

- Device: Laptop
- OS: Windows 11 Home Edition

**Comment by arrocke** [comment]
I'm not seeing this on my machine. Have you executed `nx run db:prisma migrate dev` recently?

**Comment by ilearner777** [comment]
I tried your suggestions but did not solve my problem.
Here is a screen shot from inspector.  Let me know if that helps:
![error1](https://github.com/arrocke/gloss-translation/assets/141659916/6e9fb208-5217-4bec-adbe-4c7eef47fd06)

**Comment by arrocke** [comment]
Oh, I see the problem. The language code that your browser has cached is `en` and that was changed recently. Can you try using the language picker or changing the language code in the URL to `eng`?

**Comment by ilearner777** [comment]
I found the problem.  I had saved a link to web app in chrome bookmarks as http://localhost:4200/languages/en/verses/01001001 thus preserving the 2 letter language.  I edited the bookmark to http://localhost:4200`, cleared cache and now it works fine.  Lesson learned for me on setting bookmarks!

You can close this issue.
