### ISSUE TITLE
Add Caveat point to vagrant.md

### ISSUE THREAD

**Issue by ilearner777** [arrocke/gloss-translation#257]
**Describe the bug**
`vagrant up` inconsistently times out during establishment of SSH connection

**To Reproduce**

1. Enter `vagrant up` in terminal session

**Expected behavior**
Expect command to complete without timing out.

**Environment (please complete the following information):**

- Device:Laptop
- OS: Win11

**Additional context**
Regarding Pertempo comment in PR#225 `chore: add vagrant support`

```text
How long does it usually take to boot the VM? This is at the bottom of the output of vagrant up.

=> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
```

Please confirm if you would like the following comment added to the `Caveat` section of `vagrant.md`.

4. If you experience a long pause at the point in the process shown below. The VM is up and running, but vagrant is trying to establish a SSH session to it. However, sometimes it hangs indefinitely and eventually times out. The cause is unknown.

    ```text
    => default: Waiting for machine to boot. This may take a few minutes...
        default: SSH address: 127.0.0.1:2222
        default: SSH username: vagrant
       default: SSH auth method: private key
    ```

    To free up the process before it times out, perform the following steps:

        1. Open `Oracle VM VirtualBox Manager`.
        2. Click on the name of your VM machine in the left panel. The name starts with the name of the root folder of your repository. In our case it would be `gloss-translation_....`
        3. If the VM is running, you will see a green right arrow called `Show`. It opens a new panel where you can monitor the boot process of your VM. This should free up the vagrant session and then the booting up should continue to completion.
        4. Once the vagrant session is up, you can close down the panel, without shutting down the VM, by clicking menu` Machine/Detach GUI`.

If agree with this suggestion, please assign to me for implementation.

**Comment by arrocke** [comment]
Yeah, I think this is good. I've seen this once and noticed that the networking module was taking a long time to start up.

**Comment by ilearner777** [comment]
Can you please move this to `in progress` as I do not have the authority to do so.
Thanks.
