### ISSUE TITLE
Add Docker support

### ISSUE THREAD

**Issue by ilearner777** [arrocke/gloss-translation#258]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
We have support for virtualbox VM.
It appears that there is interest in support for a docker container.

**Describe alternatives you've considered**
N/A

**Additional context**
Pertempo indicated that he was interested in this additional feature.

If you agree, feel free to assign to me for implementation.

**Comment by arrocke** [comment]
Yep, I'm good also supporting docker. I suspect a lot of developers will have docker installed and not virutalbox

**Comment by ilearner777** [comment]
I was thinking of using `smb` for syncing. Do you have a preferred method?

**Comment by arrocke** [comment]
Does vagrant not provide file syncing for docker without a plugin?

**Comment by Pertempto** [comment]
@ilearner777 should this be marked as "in progress"?

**Comment by ilearner777** [comment]
Yes, you are correct, however, I do not have authority to perform this update. Can either you or Adrian please do this on my behalf?

**Comment by ilearner777** [comment]
I have completed the adding of docker support to existing Vagrantfile.

**Issue:**
However, I have discovered that due to a bug introduced in Vagrant v2.4.0, `vagrant up` command aborts with an error during creation of a docker container. As a result, I had to develop and test using Vagrant v2.3.7.  This new bug is to be fixed in v2.4.1, which is yet to be released.

**Question:**
Do you want me to release with requirement that they use v2.3.7 with note about v2.4.0 or should we wait for v2.41 and retest with that version?

**Comment by arrocke** [comment]
There are only three of us at the moment, so I say we just get this reviewed and merged. This is another example of a question that should be asked in a PR rather than an issue
