### ISSUE TITLE
localhost:4300 get 404 error

### ISSUE THREAD

**Issue by ilearner777** [arrocke/gloss-translation#263]
**Describe the bug**
When api app is started and browser URL is set to localhost:4300, get a 404 error

**To Reproduce**

1. Sync main:origin to main:upstream
2. Pull changes to local env
3. Ran `npm install`
4. Ran `nx run db:prisma migrate dev`
5. Ran `nx serve api`
6. Clear cache on browser
7. Opened browser with URL = `http://localhost:4300`. Got 404 error
8. Manually entered URL = `http://localhost:4300\explorer`. API web page appears.

**Expected behavior**
Expected: `http://localhost:4300` to auto-redirect to `http://localhost:4300\explorer`.

**Screenshots**
![Screenshot_2](https://github.com/arrocke/gloss-translation/assets/141659916/20efd838-b187-418e-9e73-d0aa86582d92)
![Screenshot_1](https://github.com/arrocke/gloss-translation/assets/141659916/d1b2162e-bfc9-4202-bdc8-f107a656063d)
![Screenshot_3](https://github.com/arrocke/gloss-translation/assets/141659916/7decfe37-d06a-4f01-af84-960da4a18703)

**Environment (please complete the following information):**

- Device: Laptop
- OS: Win11

**Comment by arrocke** [comment]
Can you say more about why the index page of the api server should redirect to the explorer? The explorer is meant for local development and debugging only, not to act as a sort of homepage.

**Comment by ilearner777** [comment]
That is interesting. When I first forked this repo and set URL = `http://localhost:4300` I thought that at that time it auto-redirected to /explorer.  I guess I could have been mistaken.  None-the-less, thank you for correcting my misconception.

Please feel free to close this issue. :)
