### ISSUE TITLE
Lemma ID Inconsistency

### ISSUE THREAD

**Issue by Pertempto** [arrocke/gloss-translation#265]
We have an issue that has creeped into our seed data: lemma IDs of the form `H0215`, and lemma IDs without the leading zeroes: `H215`. We need to be consistent.

From what I've seen, the different import scripts use the formats like this:

### Padded with 0
- `import-bible`
     - It seems to have lemma IDs of both types: see `H0215` vs `H215` in the `LemmaForm` table
- `import-bdb`
- `import-lsj`

### No padding
- `import-bible`
     - It seems to have lemma IDs of both types: see `H0215` vs `H215` in the `LemmaForm` table
- `import-strongs`

**Comment by arrocke** [comment]
Nice catch
