### ISSUE TITLE
Webpack Dev Server Auto Reload Does Not Work in Vagrant 

### ISSUE THREAD

**Issue by Pertempto** [arrocke/gloss-translation#273]
**Describe the bug**
The auto-reload feature of the webpack dev server doesn't seem to work when running inside Vagrant.

**To Reproduce**

1. Run `nx serve web` from inside your vagrant machine (it can use the Virtualbox or Docker provider, both have the bug)
2. Open a web browser and go to `localhost:4200`
    - Verify that the web page loads correctly
3. Manually replace `{t('common:app_name')}` with `This is a test` in `Header.tsx`

**Expected behavior**
The change should automatically propagate to the web browser. The title in the header should show "This is a test" instead of "Gloss Translation"

**Environment (please complete the following information):**

- Device: Laptop
- OS: Windows 11
- Browser: Vivaldi (Chromium-based)
- Vagrant: 2.3.7

**Additional context**
This bug occurs for both the Virtualbox and Docker providers.

**Comment by arrocke** [comment]
Looks like there are [special considerations](https://webpack.js.org/guides/development-vagrant/) when running webpack with vagrant.

I think there are two viable options to resolve this:
1. Use the rsync plugin with vagrant. I don't know much about this plugin so no guarantees here.
2. Add a configuration to the dev server nx command for vagrant that uses polling according to the page I linked to above. Then you could run `nx run api:serve:vagrant` to run the dev server with the vagrant configuration

**Comment by Pertempto** [comment]
@ilearner777 if you want to take this one, go ahead and assign yourself, then update the status once you start looking into it.

**Comment by ilearner777** [comment]
Looks like I don't have authority to assign to myself.
If you can do that I will change the status.

**Comment by Pertempto** [comment]
Any progress on this? I'd be happy to help. The broken vagrant setup is causing me to loose lots of time on the project, because I keep having to setup a weird mix of DB in my VM and backend/frontend servers in my Host. I would just move my DB back to my host, but I already uninstalled the postgres Windows service.

**Comment by ilearner777** [comment]
Sorry. Didn't realize that it was causing you so much trouble.

I am working on it now.  I have a few things to try and will get back to you.
If they are successful I will post a quick fix here until 
If I need your help will let you know.

**Comment by Pertempto** [comment]
Thanks! 

Yeah, hot-reload is a pretty key part of efficient web development.

**Comment by arrocke** [comment]
I think I found a solution! I'll post a PR today
