### ISSUE TITLE
Migrate to new LSJ datasource

### ISSUE THREAD

**Issue by arrocke** [arrocke/gloss-translation#277]
**Is your feature request related to a problem? Please describe.**
Our current datasource for the LSJ is protected by a BSD license

**Describe the solution you'd like**
We should rebuild the import to use [this datasource](https://raw.githubusercontent.com/STEPBible/STEPBible-Data/master/Lexicons/TFLSJ%20extra%20-%20Translators%20Formatted%20full%20LSJ%20Bible%20lexicon%20-%20STEPBible.org%20CC%20BY.txt) instead.

**Additional context**
We will also need to sort out which words come from Bill Mounce's lexicon and either filter them out, or get permission to use.
We should also credit step bible in our project readme and potentially in the app as well

**Comment by Pertempto** [comment]
I will pause #252 in favor of this

**Comment by Pertempto** [comment]
```
 - G0001 - G5624 Strongs numbers from original set made by Strong for Greek behind the KJV  
   (G3203-G3302 which aren't used for some reason)
 - G5627 - G5799 = Greek morphology codes  (these numbers aren't used in this lexicon) 
 - G5800 - G5893 = Greek Synonyms - see http://studybible.info/strongs/G5800  (these numbers aren't used in this lexicon) 
 - G6000 - G6090 = Extra Strongs Numbers in NASB mainly for variants not known to Strong. (they remain the same so it is backward-compatible with NASB) 
 - G6100 - G9979 = Extra Greek from Apostolic Bible Project mainly for LXX words not found in NT (including Greek names that don't occur in the Hebrew) 
 - G6091 - G6099, G9980 - G9999 = Extra Greek for variants which are not included in NASB or Apostolic Bible  
 - G10000 - 19999 = Greek equivalent of Strongs Hebrew numbers for names and transliterated words eg  Abagtha (H0005) = G10005. When there is a NT equivalent, this is the STEP_LexicalTag
 - G20000 - G20199 = Words where  the Full LSJ entry refers to the LXX, but they are not referred to in the AB tagging because they only occur in non-Protestant canons or in MSS other than Vaticanus (used by AB)
```

Do we only need the original set?

**Comment by arrocke** [comment]
Yeah, let's start there. The file I linked to has just those entries

**Comment by Pertempto** [comment]
The file you linked to is titled "TFLSJ - Translators Formatted full LSJ Bible lexicon extra"

It only seems to have numbers from G6000 and above.

**Comment by Pertempto** [comment]
[Here](https://raw.githubusercontent.com/STEPBible/STEPBible-Data/master/Lexicons/TFLSJ%20%200-5624%20-%20Translators%20Formatted%20full%20LSJ%20Bible%20lexicon%20-%20STEPBible.org%20CC%20BY.txt) is the file containing the base set, from this [directory](https://github.com/STEPBible/STEPBible-Data/tree/master/Lexicons). Hopefully it is fine to use, it seems to be licensed the same.
