### ISSUE TITLE
make gloss approval more discoverable.

### ISSUE THREAD

**Issue by arrocke** [arrocke/gloss-translation#282]
**Is your feature request related to a problem? Please describe.**
In all user interviews I've done, users aren't discovering that glosses can be approved and unapproved. Additionally, there is no way to approve/unapprove glosses on a mobile device (including tablets) since we can't listen for Enter on them.

**Describe the solution you'd like**
One option is to add a button that's not in the tab sequence after each input to either approve or unapprove the gloss. We can additionally only make it appear when the input is focused, and also put the keyboard shortcut in a tooltip.

**Comment by arrocke** [comment]
Here is an example of what this could look like. When a gloss input is focused, a button appears to the left side (right for greek) to either approve or unapprove depending on the state. Hovering on the button would show as a tooltip either `Approve (Enter)` or `Unapprove (Esc)` to give a little discoverability to the keyboard shortcuts.




![Image](https://github.com/arrocke/gloss-translation/assets/11968925/dae1e5b7-0e50-4ed3-9d92-811468b7a4a8)

**Comment by arrocke** [comment]
@Pertempto @BethedenMinistries Let me know what you think of this solution. We'll put this in the queue to be developed once we are in agreement

**Comment by Pertempto** [comment]
I like the idea of a button that appears when the input is focused, but how would that affect accessibility

**Comment by arrocke** [comment]
Because we've got the keyboard shortcuts, the button doesn't need to be in the tab sequence. That should be sufficient for accessibility.

**Comment by Pertempto** [comment]
Makes sense 👍👍

The tooltips are a good idea too

**Comment by Pertempto** [comment]
The input width will shrink when focused to make room for the button? That doesn't seem ideal, the inputs already can seem too narrow as they are.

**Comment by arrocke** [comment]
We are setting the width of each word block based on the largest width of the Hebrew/Greek, reference gloss, and gloss input. So if we change the calculation for the input width to account for the button then there will be space. Notice in the screenshot that the inputs extend beyond the Hebrew and the reference gloss so that when the button appears, there is still sufficient room to render the gloss. We'll need to set a larger min width so that when there is no gloss, the input is still wide enough to input something.
