### ISSUE TITLE
missing words in Hebrew

### ISSUE THREAD

**Issue by arrocke** [arrocke/gloss-translation#285]
**Describe the bug**
There are words in the current app that aren't in this one.

**To Reproduce**
Comare Obadiah 5 in hebrewgreekbible.online and globalbibletools.com. There are words missing.

**Expected behavior**
These missing words should be there.

**Additional context**
This appears to be caused by how we imported data from the old app. Our filter for which elements in the data file filtered out Hebrew words with no lemma ID

**Comment by arrocke** [comment]
@BethedenMinistries Is there a list of changes that have been made to the OpenScriptures data since it was taken from their repo? In order to get proper alignment with BDB entries, I need to go back to their data

**Comment by BethedenMinistries** [comment]
I wasn't aware that Sheldon used Openscriptures data. This is definitely a question for him.
