### ISSUE TITLE
Error logging into web app as devyn61@ethereal.email

### ISSUE THREAD

**Issue by ilearner777** [arrocke/gloss-translation#301]
**Describe the bug**
Get pop-up error message when logging into web app as user: `devyn61@ethereal.email` with password: `asdf1234`

**To Reproduce**

1. Start `nx serve api`
2. Start `nx server web`
3. On web page, click on `Log In` menu item
4. Enter  user: `devyn61@ethereal.email` with password: `asdf1234`
5. Click `Login In` button.

**Expected behavior**
Expect to be able to login as  `devyn61@ethereal.email` 

**Screenshots**

![Screenshot_2](https://github.com/arrocke/gloss-translation/assets/141659916/0e9b7542-ffe0-4162-bb1a-c4ba6f05f338)

**Environment (please complete the following information):**

- Device: Laptop]
- OS: Win11
- Browser: chrome
- Version: 120.0.6099.111 (Official Build) (64-bit)

**Additional context**
This is what is documented in our `contributing.md` document.  If the process to log in has changed permanently, would be good to update the documentation.

**Comment by arrocke** [comment]
Yep, that ethereal.email address was back when we used that site to be able to test email sending. Now in dev environments, we just log the sent email to the console. I changed the admin email in the database seed to be `platform_admin@example.com`, so we need to update the docs

**Comment by ilearner777** [comment]
@arrocke This is not showing up on project board.  Can you please fix?
