### ISSUE TITLE
add tab panel to sidebar

### ISSUE THREAD

**Issue by arrocke** [arrocke/gloss-translation#303]
* Sidebar should have a set of tabs underneath the word
* Initial tab will be titled `Lexicon` and show either the BDB or the LSJ

![Image](https://github.com/arrocke/gloss-translation/assets/11968925/a66633a3-63e1-49a8-886b-f7bd4aee91e4)

**Comment by arrocke** [comment]
I think we can use HeadlessUI's tab panel: https://headlessui.com/react/tabs. We can just build it into the sidebar for now rather than building out our own tab component. No reason to abstract a tab panel since we are only using it once.

**Comment by Pertempto** [comment]
great, thanks!

**Comment by Pertempto** [comment]
What's the current target list of tabs? I know we don't want the strong's anymore.

**Comment by arrocke** [comment]
It's a little up in the air. I think for sure we will have Lexicon, Notes, Comments. We may also add Usage which will have the other verses a word was glossed, and maybe a Tools tab for find and replace. These two aren't flushed out yet.
