### ISSUE TITLE
Branding and design

### ISSUE THREAD

**Issue by arrocke** [arrocke/gloss-translation#325]
We have this [design concept](https://coolors.co/visualizer/f0edd9-83c5be-006d77) and icon:
<img src="https://github.com/arrocke/gloss-translation/assets/11968925/512963ce-e538-4966-b987-5199cb7feb7d" width="100" />

We'll want to figure out how to incorporate that into the design of the site

## stories
- #326 
- #329 
- #331  
- #362
- #355 
- #353 
- #364

**Comment by Pertempto** [comment]
What design concept and icon set? Did you forget the link?

**Comment by arrocke** [comment]
Woops, you are right. Updated
