### ISSUE TITLE
language permissions aren't refreshed when you modify them on yourself

### ISSUE THREAD

**Issue by arrocke** [arrocke/gloss-translation#333]
**Describe the bug**
When you add or remove language permissions for yourself, the client doesn't update with your new permissions.

**To Reproduce**
1. Log in as an admin.
2. Add a new language
3. Confirm that you can't translate the language
4. Add yourself as a translator
5. Try to translate the language - confirm your permissions haven't updated
6. Now refresh the page
7. Confirm that your permissions have updated and you can translate the language.

**Expected behavior**
The client should refetch your language permissions when you make a change to yourself.

**Comment by Pertempto** [comment]
@arrocke do you need to change the project settings so that @tycebrown can assign himself to issues

**Comment by arrocke** [comment]
@Pertempto He should have access

**Comment by tycebrown** [comment]
@arrocke Could you double-check? Under assignees, I only see "No one assigned."
