### ISSUE TITLE
preview verses in lexicons

### ISSUE THREAD

**Issue by arrocke** [arrocke/gloss-translation#336]
Verses in lexicon entries should be clickable so translators can see the hebrew and glosses in their language without leaving the verse they are currently working on

**Comment by arrocke** [comment]
An idea for how this could look: https://codepen.io/arrocke/pen/abxbVPY

**Comment by arrocke** [comment]
Here is what I want this to look like. This will be tricky since we'll need to insert an element into the lexicon HTML manually and use a react portal to render the contents within.

![Image](https://github.com/globalbibletools/gbt/assets/11968925/7374c742-034e-4c7a-a23e-e705445b22fb)

**Comment by Pertempto** [comment]
I'll try this one. Never worked with react portals before so there will be a little bit of a learning curve.
