### ISSUE TITLE
Manage Button Not Focusable

### ISSUE THREAD

**Issue by Pertempto** [arrocke/gloss-translation#349]
**Describe the bug**
The manage language button on the translation page is outside of the tab series.

**To Reproduce**
1. Go to the translation page
2. Try to tab to the manage language button

**Expected behavior**
The manage language button should be focusable by the keyboard.

**Environment (please complete the following information):**

- Device: Laptop
- OS: Windows 11
- Browser: Vivaldi

**Additional context**

This shows up in the changes from #347

**Comment by arrocke** [comment]
I'm not seeing this on Chrome. It's working for me

**Comment by tycebrown** [comment]
I'm not having this problem either. Tested on Brave (chrome-based) and Edge.

**Comment by arrocke** [comment]
@Pertempto Now that you have the correct version of tailwind, are you still seeing this issue and #351?

**Comment by Pertempto** [comment]
#351 is fixed, but I still see this bug, even on the real site. It doesn't happen for me in Firefox or Edge, just Vivaldi. It must just be a some setting or something I broke in vivaldi 🤷🏽
