### ISSUE TITLE
User Role Dropdown Selector not Focusable

### ISSUE THREAD

**Issue by Pertempto** [arrocke/gloss-translation#351]
**Describe the bug**
The user role dropdown in the invite user dialog is not focusable by the keyboard.

**To Reproduce**

1. Go to the admin page
2. Click on the users section
3. Click the Invite User button
4. Try to tab to the role dropdown

**Expected behavior**
The role dropdown should correctly receive keyboard focus

**Environment (please complete the following information):**

- Device: Laptop
- OS: Windows 11
- Browser: Vivaldi

**Additional context**
Relies on changes from #347

**Comment by arrocke** [comment]
I'm not seeing this in Chrome. It's working for me

**Comment by tycebrown** [comment]
Hmm... I'm not seeing this either. Weird. Test on Brave (chrome-based) and Edge.

**Comment by Pertempto** [comment]
Doesn't happen for me anymore
