### ISSUE TITLE
Not Enough Space Above Input Message

### ISSUE THREAD

**Issue by Pertempto** [arrocke/gloss-translation#352]
**Describe the bug**
There is not enough space between the input and the message below it

**To Reproduce**

1. Go to the admin page
2. Go to the languages section
3. Type in an invalid language code like "test"

**Expected behavior**
The error message should have more space above it.

**Screenshots**
![image](https://github.com/arrocke/gloss-translation/assets/17209828/208622f9-0bbf-4f90-8531-3e75ddfbd8fb)

**Environment (please complete the following information):**

- Device: Laptop
- OS: Windows 11
- Browser: Vivaldi

**Additional context**
Requires changes from #347

**Comment by arrocke** [comment]
I think I don't like the space between the input and the outline. I think we can just remove the offset and then this issue should go away
