### ISSUE TITLE
Submitting Text Needs Space

### ISSUE THREAD

**Issue by Pertempto** [arrocke/gloss-translation#353]
**Describe the bug**
There is not sufficient spac

**To Reproduce**
I've seen this happen in many places that involve submitting something. Here is one example

1. Open the dropdown on the right side of the nav bar
2. Click on "Profile"
3. Change the user name

**Expected behavior**
The submitting text should be only for screen readers, or have better spacing.

**Screenshots**
![image](https://github.com/arrocke/gloss-translation/assets/17209828/16432643-5625-4c3c-8f49-5c9de7897d89)

**Environment (please complete the following information):**

- Device: Laptop
- OS: Windows 11
- Browser: Vivaldi

**Additional context**
This relies on the changes from #347

**Comment by arrocke** [comment]
I think I want to replace the submitting indicator with a new component `SubmitButton` that renders the loading spinner and text `Submitting`. I think that will be simpler than a separate ui element. @Pertempto Do you want to work on this?

**Comment by Pertempto** [comment]
Yep!
