### ISSUE TITLE
Landing Page Width Issues

### ISSUE THREAD

**Issue by Pertempto** [arrocke/gloss-translation#354]
**Describe the bug**
On desktop, the landing page has a horizontal scrollbar for no apparent reason.

**To Reproduce**

1. Open the landing page on desktop
2. Check if there is a horizontal scrollbar on the content of the page

**Expected behavior**
No horizontal scrollbar on the content of the landing page

**Screenshots**
![image](https://github.com/arrocke/gloss-translation/assets/17209828/da892e6e-9dd1-43c4-a795-a766db58cdc6)

**Environment (please complete the following information):**

- Device: Laptop
- OS: Windows 11
- Browser: Vivaldi

**Additional context**
Interestingly, if I open the chrome dev tools to try emulating different screen sizes, the scrollbar goes away. 🤔

**Comment by Pertempto** [comment]
@arrocke I'd enjoy taking this one.

**Comment by arrocke** [comment]
I'm pretty sure the horizontal scrollbar is caused by the presence of the vertical scrollbar. For some reason, on some computers the scrollbar increases the width of the site

**Comment by tycebrown** [comment]
Could the problem be with the `::after` pseudo element with its right border width set to `100vw`?[https://stackoverflow.com/questions/30489594/prevent-100vw-from-creating-horizontal-scroll](https://stackoverflow.com/questions/30489594/prevent-100vw-from-creating-horizontal-scroll)

**Comment by Pertempto** [comment]
> I'm pretty sure the horizontal scrollbar is caused by the presence of the vertical scrollbar. For some reason, on some computers the scrollbar increases the width of the site


> Could the problem be with the `::after` pseudo element with its right border width set to `100vw`?https://stackoverflow.com/questions/30489594/prevent-100vw-from-creating-horizontal-scroll

I think you are both right. I've seen people recommend against using `100vw` because of this annoying behavior. I'll look into it.
