### ISSUE TITLE
Approve all glosses button

### ISSUE THREAD

**Issue by arrocke** [arrocke/gloss-translation#357]
In the translation toolbar, add a button to approve all glosses in the verse as they are. This should only send one network request rather than one for each word. We also need the keyboard shortcut Alt+A for the same action

![Image](https://github.com/arrocke/gloss-translation/assets/11968925/7e223784-4d5b-472a-8b3d-226f13e2ac9d)

**Comment by tycebrown** [comment]
I should (finally) have this done by the end of today :+1:
