### ISSUE TITLE
Improve Landing Page Text Legibiliity

### ISSUE THREAD

**Issue by Pertempto** [arrocke/gloss-translation#360]
**Describe the bug**
The sentence in the middle of the landing page is not very legible. Most of the text is white on an orange background. Some of the text is white on a black background, which is distracting.

**To Reproduce**

1. Go to the landing page
2. Read the sentence in the middle of the page

**Expected behavior**
We need that sentence to be as legible as possible, it is meant to grab the viewer's attention and lead them to explore the rest of the site.

**Screenshots**
I have marked the problem areas

![image](https://github.com/globalbibletools/gbt/assets/17209828/bb8cb3e5-c17c-4331-8846-b4b43aa9d67b)

**Comment by Pertempto** [comment]
@arrocke I don't have any way to scientifically prove that the mixed background is causing legibility issues, it's just something I notice every time I visit the landing page. That sentence sticks out to me, but in a bad way. The rest of the page looks very professional, that sentence with poor legibility doesn't.

**Comment by Pertempto** [comment]
@arrocke For some reason it is by default adding the issue to the project under your personal account, not the project under the organization. 

![image](https://github.com/globalbibletools/gbt/assets/17209828/2e8be490-5d96-440c-b40d-017f56400827)


Maybe some setting needs configured differently?

**Comment by arrocke** [comment]
Yeah, Andrew asked me to darken the image a bit. I checked with a tool and the new darkness seems to be sufficient.
