### ISSUE TITLE
cache bust styles output in landing site

### ISSUE THREAD

**Issue by arrocke** [arrocke/gloss-translation#364]
The landing site's css is cached in the browser. We need to cache bust this somehow when it's contents change

**Comment by Pertempto** [comment]
I think this is kinda high priority so the landing page doesn't look terrible for people who previously visited the page after we update the styling.

![image](https://github.com/globalbibletools/gbt/assets/17209828/1a4ff4d7-3cc8-4621-8231-410084710ed9)
