### ISSUE TITLE
Indicate which words have notes in translation line

### ISSUE THREAD

**Issue by arrocke** [arrocke/gloss-translation#383]
* To the left of the hebrew and right of the greek in the translation line, add the [note-sticky](https://fontawesome.com/icons/note-sticky?f=classic&s=solid) icon if the word has either a footnote or a translator note
* If the user does not have access to translator notes, only show the icon if there is a footnote
* Clicking the icon should open the note sidebar and put focus on the first text editor if the user has edit permissions

**Comment by tycebrown** [comment]
This should be done by today :+1:
