### ISSUE TITLE
Change Url to chapter url

### ISSUE THREAD

**Issue by hamar030** [arrocke/gloss-translation#386]
I have an idea about to change url /verses/(digit_number) to /script/chapter for example like /bamidbar/1 or /numbers/1

Im interested with this project, maybe i can help this project,
i've been create an simple bible too, check my project for your reference
Website: [webile.netlify.app](https://webible.netlify.app/bible)
Github: [hamar030/webible](https://github.com/hamar030/webible)

**Comment by arrocke** [comment]
Thanks for opening a ticket. Can you say more about what problem this solves or what benefit changing the URL format brings?
