### ISSUE TITLE
Import Language - Unique Constraint Fails

### ISSUE THREAD

**Issue by Pertempto** [arrocke/gloss-translation#388]
**Describe the bug**
Running the import language lambda functions triggers a lot of prisma errors.

**To Reproduce**

1. Run the import language process.
    - See the instructions in `docs/lambda-functions.md`

**Expected behavior**
No error messages while importing a language

**Error**
```
Invalid `prisma.gloss.createMany()` invocation:
Unique constraint failed on the fields: (`wordId`,`languageId`)
    at _n.handleRequestError (/var/task/main.js:563:6854)
    at _n.handleAndLogRequestError (/var/task/main.js:563:6188)
    at _n.request (/var/task/main.js:563:5896)
    at async l (/var/task/main.js:568:10871)
    at async Runtime.lambdaHandler [as handler] (/var/task/main.js:810:11) {
  code: 'P2002',
  clientVersion: '5.10.2',
  meta: { modelName: 'Gloss', target: [ 'wordId', 'languageId' ] }
}
```

**Environment**

- Device: Laptop
- OS: Windows 11

**Additional context**
`await client.gloss.createMany` is called twice in the lambda function code, I think this is what is causing the problem.

**Comment by Pertempto** [comment]
@arrocke I think this was caused by the changes from #382

**Comment by arrocke** [comment]
@Pertempto Thanks for catching this. I'll look at it this week. The new import logic isn't released yet to the lambda, so this isn't broken in production yet
