### ISSUE TITLE
Bug: blurring the notes editor can lead to loss of data

### ISSUE THREAD

**Issue by tycebrown** [arrocke/gloss-translation#392]
**Describe the bug**
When the user switches focus from the notes editor of one word to another and then blurs, the notes of the second word will contain the contents of the first.

**To Reproduce**

1. Find two words with translator notes.
   - This bug can be reproduced with footnotes as well 
2. Open the notes tab for the first word. Focus on translator notes editor and observe its content.
3. Open the notes tab for second word. Focus on translator notes editor and observe its content.
4. Blur. Reload the page. 
5. Confirm that the notes for the first word have been copied to (or swapped with) the second.
  

**Expected behavior**
Notes for the second word should not have changed, neither should the notes for the first word.

**Screenshots**
Here is a demonstration of the bug:

https://github.com/globalbibletools/gbt/assets/91034018/054deaf6-f9dc-4142-abca-0964ee253d09

**Environment (please complete the following information):**

- Device: Laptop
- OS: Window
- Browser: brave (chrome-based)
- Version: v1.65

**Additional context**
I think the problem lies in the hidden input in `RichTextInput`.

**Comment by Pertempto** [comment]
Really good catch! This is a severe bug, but tricky to track down!
