### ISSUE TITLE
Bug: notes display not updated

### ISSUE THREAD

**Issue by tycebrown** [arrocke/gloss-translation#396]
**Describe the bug**
Modifications to the contents of a word's notes are not displayed. The "Updated At ..." message does not appear/is not updated. It may be that the database is not updated/queried from correctly. Or, it could just be a frontend problem

**To Reproduce**
Steps to reproduce the behavior (from [Addison's comment](https://github.com/globalbibletools/gbt/pull/394#issuecomment-2102296736) in PR #394):

1. Click on a gloss input
2. Go to the notes tab
3. Enter a footnote
4. Click outside the footnote input
   - For some reason the "updated at" text doesn't show up
5. Click on a different gloss
6. Click on the original gloss
7. The footnote is gone

**Expected behavior**
The note's content should be updated and displayed to the user.
_Tenative: It appears, at the current moment, that the database does update, ~~but the network request responds with the old content~~ but the query used to fetch the notes does not work properly._

**Screenshots**

**Environment (please complete the following information):**

- Device: Laptop
- OS: Windows
- Browser: Brave (Chrome based)
- Version: [e.g. 22]

**Comment by tycebrown** [comment]
Alright, I think I've found part of the issue. The notes query is returning multiple entries with the same `wordId` but different `translatorNoteContent` and `footnoteContent`.

**Comment by tycebrown** [comment]
@arrocke Would that be because the query `LEFT JOIN`s the `PhraseWord`s, which are/can be connected to multiple `Word`s?

**Comment by arrocke** [comment]
I doubt that's the problem because our api calls prevent that scenario. From what I can see the query that executes immediately after the update, the timestamp is still 0. I'm not seeing the footnote disappear.

**Comment by arrocke** [comment]
Found it! The [notes query](https://github.com/globalbibletools/gbt/blob/main/packages/api/pages/api/languages/%5Bcode%5D/verses/%5BverseId%5D/notes.ts#L32-L33) is swapping the footnote and translator note timestamps
