### ISSUE TITLE
bug: notes editor update issue

### ISSUE THREAD

**Issue by tycebrown** [arrocke/gloss-translation#401]
**Describe the bug**
Let's say there are two words which don't have any notes. If the user adds notes to the first word, and then switches focus to the second word, the notes editor will still display the notes added to the first word.

**To Reproduce**

1. Find two words without notes.
2. Open the notes tab for the first word. Enter any content into one of the notes editors.
3. Switch focus to the second word.
4. Confirm that the editor still has the notes content from the first word.

**Expected behavior**
The editor of the second word should be empty. 

**Environment (please complete the following information):**

- Device: Laptop
- OS: Windows
- Browser: Brave 
- Version: 1.65.132

**Screenshots**

https://github.com/globalbibletools/gbt/assets/91034018/caf0abf3-582d-4494-a768-894dd6fa2f86

**Comment by Pertempto** [comment]
I've seen this same bug several times 👍🏽

**Comment by arrocke** [comment]
@tycebrown I'm also seeing that when you switch languages, the same thing happens
