### ISSUE TITLE
add e2e testing

### ISSUE THREAD

**Issue by Pertempto** [arrocke/gloss-translation#403]
**Is your feature request related to a problem? Please describe.**

This is a pretty low priority idea, but I thought it might be useful. I've noticed that there are some common operations that we continually re-test as we tinker with the glossing frontend/backend

- Add glosses
- Approve glosses
- Approve all glosses
- Add notes

**Describe the solution you'd like**

We could save time by automating the testing of these common situations with [Playwright](https://playwright.dev). Ideally, we would run e2e tests in a GitHub action on every PR, but we can save that for a future issue.

**Describe alternatives you've considered**

There are other e2e frameworks out there. [Cypress](https://www.cypress.io) is one that I know of.

**Comment by Pertempto** [comment]
@arrocke If i tinkered with implementing some basic playwright tests, would you accept them? What is your opinion about and/or experience with e2e testing?


I'm not really very familiar with e2e testing, so I thought this would be a great way for me to build some experience while also saving us time long term by providing some guards against some of the recent regression bugs we've ran into (#398, #401). I also thought it would be a good way for me to contribute without having to directly use react 😅 (I've kind of burnt out on react lately if you couldn't tell)

**Comment by arrocke** [comment]
I'm not opposed to e2e tests in the abstract. We are transitioning to playwright from cypress at work right now and have had a good experience. My only hesitation is whether that investment is worth it at this point. If we end up rebuilding this in a vscode extension a year from now, our time is better spent experimenting with vscode.

The short of it is that I would absolutely accept PRs for e2e tests, but I think investigating and planning for lexicon work with vscode is more important in the bigger picture.

**Comment by Pertempto** [comment]
Alright I will continue tinkering with VS code then, that makes a lot of sense
