### ISSUE TITLE
help page 

### ISSUE THREAD

**Issue by tycebrown** [arrocke/gloss-translation#408]
**Is your feature request related to a problem? Please describe.**
We have multiple ctrl codes and keyboard commands which are practically hidden from the user.

**Describe the solution you'd like**
I propose we have a help page which lists all the ctrl codes and any other information we think would be helpful to the user.

**Describe alternatives you've considered**
Perhaps we could have some sort of tutorial?

**Additional context**
- This wouldn't have to be a separate page. It might be better in a modal dialog.
- We could put an icon button to open the page right next to the username

**Comment by arrocke** [comment]
Andrew wants us to add a note to the help page that indicates that all data is backed up. Translators worry about their data being lost
