### ISSUE TITLE
export to GitHub

### ISSUE THREAD

**Issue by arrocke** [arrocke/gloss-translation#415]
* Completed books should be exported to a GitHub repo with a creative commons license
* This should happen at most once a night, maybe once a week
* Changes to completed chapters should be exported as well
* We'll also need to export the Hebrew/Greek data we use so others can reference that to align our data with theirs

**Comment by tycebrown** [comment]
It looks like we could setup a [cron job](https://vercel.com/docs/cron-jobs#cron-expressions) to periodically backup all completed books to github.

**Comment by arrocke** [comment]
We will build this as a worker in the new repo like we did for the language import. I'm still trying to figure out how we can run that on AWS

**Comment by arrocke** [comment]
The export format should be something like this:
```
lang
book
  bookId
  verse
    verseId
    chapterNumber
    verseNumber
    words
      wordId
      gloss
      footnote
      linkedWords
```

**Comment by arrocke** [comment]
@tycebrown Are you good to tackle this one next?

**Comment by tycebrown** [comment]
Do you want me to write this on `gbt` or `platform`?

**Comment by arrocke** [comment]
In `platform`. You'll see a workers directory in that project

**Comment by tycebrown** [comment]
@arrocke Why is it that we need `wordOrder`, since the each `wordId` already corresponds to a specific word in the text?

**Comment by arrocke** [comment]
Fair point. We can leave that out
