### ISSUE TITLE
make word columns variable-width

### ISSUE THREAD

**Issue by Pertempto** [arrocke/gloss-translation#55]
The columns for each word in the original language should be variable width. They look way too big for short words, and don't handle long glosses in an ideal way either.  

![image](https://user-images.githubusercontent.com/17209828/236426349-6319f85f-c92c-42e9-9008-ec94eb8eae2d.png)

**Comment by arrocke** [comment]
Yeah, this is the right idea. I really wrestled with the CSS to get this to look right, and decided to push it off until later. We should do this though.

**Comment by Pertempto** [comment]
From @BethedenMinistries in the whatsapp messages:
> Also, you may already be working on this, but my preference would be to have the English and Hebrew both centered over the gloss field.  

I will try this, but I'm not sure how great it will look, since the Hebrew and English will be different lengths.

> Also, how hard would it be to have the gloss field automatically adjust its size to the text inside it?

This is the main goal of the issue.
