### ISSUE TITLE
use prettier for consistent code formatting

### ISSUE THREAD

**Issue by Pertempto** [arrocke/gloss-translation#56]
[Prettier](https://www.npmjs.com/package/prettier) is great. The fact that it is opinionated means you don't have to waste time arguing about a code format. You can hook it up with tools like [pretty-quick](https://www.npmjs.com/package/pretty-quick) with a [husky](https://www.npmjs.com/package/husky) hook to automatically format changed files at commit. This way all the code formatting is consistent and you don't get PRs fully of formatting changes.  

I think this should be done before we add lots of developers to the project. (or add too many more files - they will all need formatted)

**Comment by Pertempto** [comment]
@arrocke If you approve of this one, I can set it up

**Comment by Pertempto** [comment]
It looks like we already have a `.prettierrc` file. This issue would then be for setting up automatic formatting hooks.

**Comment by arrocke** [comment]
Yeah `nx` comes with a command `nx format` that runs prettier in the project. In my job, we use `lint-staged` and `husky` with this config. Using `nx affected` only lints the projects that have changed rather than the entire project.
```js
module.exports = {
  '**/*.{js,ts,tsx}': [
    'nx affected:lint --fix --files',
    'nx format:write --files'
  ],
  '!**/*.{js,ts,tsx}': 'nx format write --files'
}
```
