### ISSUE TITLE
match verse references algorithmically

### ISSUE THREAD

**Issue by arrocke** [arrocke/gloss-translation#57]
## acceptance criteria
* Use an algorithm to fuzzy match book names
* Generate the regex to match verse references from the format string
* Remove the book match arrays from the translation strings
* Add bible namespace for es

**Comment by Pertempto** [comment]
I don't know if we can totally get rid of the match arrays. What about "1 Kings" and "First Kings"? I think we would want to support both versions but maybe "First Kings" is unnecessary.

**Comment by arrocke** [comment]
My thought would be to see how far we can get without the list. In general, the important matches are the shorter ones since those will be more common. I think it is more likely that we will need to revamp this because some other languages doesn't work with the algorithm.

**Comment by Pertempto** [comment]
Future idea: show matched book names in a dropdown as the user types in the verse selector (similar to Bible Hub). Save this for future issue so that we can get the MVP done quickly.
