### ISSUE TITLE
User administration

### ISSUE THREAD

**Issue by arrocke** [arrocke/gloss-translation#59]
## acceptance criteria
* Users
  * Log in with email or password
  * Can reset their password
  * Can update their profile information
  * Access the languages they have permissions for
* System admins
  * Can invite new users
  * Can grant admin privileges to other users
  * Can create new languages, and invite users to languages
* Language permissions
  * Every user on a language can have edit and/or admin privileges
  * Language admins can invite new users, and change permissions

## stories
* #65
* #66
* #67
* #68
* #69
* #70
* #71
* #72
* #73

**Comment by arrocke** [comment]
@BethedenMinistries @LouKehler Do either of you have a preference for how users log in? I would love to not have to manage passwords and use an email link login instead.

**Comment by LouKehler** [comment]
It doesn't matter to me as long as it is secure and easy.

**Comment by BethedenMinistries** [comment]
I agree with both of you.
