### ISSUE TITLE
data import

### ISSUE THREAD

**Issue by arrocke** [arrocke/gloss-translation#60]
## acceptance criteria
* As a language admin, I can select a language from the old app to import
* This data overwrites all of the existing glosses for the language

**Comment by Pertempto** [comment]
What will this all involve? I know next to nothing about the data from the old app.

**Comment by arrocke** [comment]
Here is how I think this could work:

1. Load language list by loading source from hebrewgreekbible.online. This file has a variable called `glossLanguageNames` that we can extract with a regex that we can use to render a dropdown to select the language to import
2. Data files are stored at URLs like https://hebrewgreekbible.online/EnglishGlosses/GenGloss.js. We can use the selected language and parse of all of the files with JSON.parse after removing `var glosses =` and comments.
3. Now we can insert glosses into our database from this data. Data is in a nested array of chapters, verses, words, word data. We can assume the order of words in a verse matches outs since our data source is the same.

**Comment by Pertempto** [comment]
> Now we can insert glosses into our database from this data

What method should I use for inserting the data.

**Comment by Pertempto** [comment]
Ahhh. At first I thought we were doing the data import in one sweep in a PR. Now I see that you want the data import to be triggered by the admins, and ran in the API. 👍🏽

**Comment by Pertempto** [comment]
This is my first time writing API code for this project, so the first draft will be pretty terrible. Hopefully you can bare with me.

**Comment by Pertempto** [comment]
@arrocke If it is ok with you, I'll do a series of smaller PRs for this one issue, each one building on the last. That way I can get feedback from you quicker, and get back on track earlier.

**Comment by arrocke** [comment]
That's ok with me, just be clear in your PR what's included

**Comment by Pertempto** [comment]
What library do you recommend using in node.js for making the requests to hebrewgreekbible.online

**Comment by arrocke** [comment]
We are on node 18 so we can just use fetch!

**Comment by Pertempto** [comment]
> We are on node 18 so we can just use fetch!

Oh this API is really nice and simple!

**Comment by Pertempto** [comment]
@arrocke I was working on creating a separate language import page, but it just makes a lot of duplicate code.
When a user imports a language, they need to input the code and name (because the old names were all in English).


What do you think about this idea?
* We would have one language creation page
* At the top of the page, it gives a dropdown to select an import language
* The dropdown also has the option "None"
    * Maybe there is a better name
    * Selecting this option triggers the normal language creation API
* If they select an import language, we trigger the language import API

This saves duplicate code and solves the situation where language admins accidentally create languages on our site and then realize that they actually wanted to import the language from the old site. By always having the language dropdown they will see those options.

**Comment by arrocke** [comment]
I've sent a question to the group about this. I was envisioning that this could go on the manage language page so that as people are trying out the app, they could import from the existing app multiple times until they decide to make the final switch

**Comment by Pertempto** [comment]
<img width="257" alt="image" src="https://github.com/arrocke/gloss-translation/assets/17209828/aadb992c-7c8a-4cd5-a5ba-dfa6124c3241">

**Comment by Pertempto** [comment]
so you're thinking they would click the "manage" button and then import on an existing language in our site?
i was envisioning importing as part of the setup of a language. this totally changes things 😆

**Comment by arrocke** [comment]
Yeah, that's why I've asked the question to the group. We need to understand how this is going to be used. 

The other thing that we need to keep in mind is that most users won't have permissions to create new languages, so it may work better for Andrew to give somebody access to their language and then they can do the import on their own terms.

**Comment by Pertempto** [comment]
Ahh that makes sense. I didn't think about the permissions thing.

So go ahead with the overwrite strategy like we discussed in the group?

**Comment by arrocke** [comment]
Yes, i think that's the right approach

**Comment by Pertempto** [comment]
Something like this
<img width="304" alt="image" src="https://github.com/arrocke/gloss-translation/assets/17209828/bbf73bfb-32bf-4bd9-8f90-2d36da8b69b8">

**Comment by Pertempto** [comment]
I guess I need to use a `Link` here instead of a `Button`, but the `Button` looks way nicer.

**Comment by Pertempto** [comment]
<img width="409" alt="image" src="https://github.com/arrocke/gloss-translation/assets/17209828/9186c79f-4b22-4bd5-bceb-2c7006200b2b">
<img width="375" alt="image" src="https://github.com/arrocke/gloss-translation/assets/17209828/68bab8e0-747f-4eb9-afa6-ff2cc31071fb">

**Comment by arrocke** [comment]
Yeah, look nice! We can style a link to look like a button
