### ISSUE TITLE
Lexicons

### ISSUE THREAD

**Issue by arrocke** [arrocke/gloss-translation#61]
## description
* Both the BDB for Hebrew and the LSJ for Greek are visible in the sidebar when the original word is selected
* Strongs glosses are shown as a quick glance

![Image](https://github.com/arrocke/gloss-translation/assets/11968925/2c9866c7-6272-43b5-9a0b-8183c03007a0)

## datasources
* [BDB](https://github.com/unfoldingWord/Brown-Driver-Briggs-Enhanced)
* [strongs](https://raw.githubusercontent.com/morphgnt/strongs-dictionary-xml/master/strongsgreek.xml)
* [StepBible data](https://github.com/STEPBible/step/tree/master/step-core-data/src/main/resources/com/tyndalehouse/step/core/data/create/lexicon)

## stories
* #155 
* #161 
* #162 
* #163 
* #164 
* #165 
* #166 
* #252 
* #248 
* #262
* #280 
* #277

**Comment by arrocke** [comment]
@BethedenMinistries Are we ok only supporting English lexicons a the moment? Are most of our potential users at this stage English speaking? Or would we be better off working on a find and replace tool first?

**Comment by BethedenMinistries** [comment]
Yes, that's fine. All the people I have personally recruited can manage with English. @LouKehler would need to comment on the rest who are using it.

**Comment by LouKehler** [comment]
The only non-English lexicon currently available is the Chavez for Spanish so if they are able to manage with English then great.
