### ISSUE TITLE
Reference translation

### ISSUE THREAD

**Issue by arrocke** [arrocke/gloss-translation#62]
## acceptance criteria
* language admins can establish a prioritized list of reference translations
* the app will search through the list for a translation that has that verse
* if no translation is found a helpful message is displayed instead

## stories
* #154 
* #171 
* #208 
* #172

**Comment by arrocke** [comment]
@BethedenMinistries @LouKehler Where can we find the data of these translations, and what formats are they generally using?

**Comment by LouKehler** [comment]
They come from a few sources. Most are coming in verse-by-verse format from:
  https://github.com/getbible/Unbound-Biola
others in USFM format come from:
  https://open.bible/resources/

**Comment by arrocke** [comment]
[this issue](https://github.com/getbible/Unbound-Biola/issues/16#issuecomment-569151968) on that github repository indicates that these sources might have mistakes and that [their new api](https://getbible.net/api) is meant be better in sync with data from [here](https://crosswire.org/sword/modules/ModDisp.jsp?modType=Bibles)

So would it make sense to support both the USX format from open.bible, as well as this getbible API? I'd prefer to use USX over USFM since USX is xml based.

**Comment by LouKehler** [comment]
I found USFM more convenient because I already had scripts to handle these files from Paratext. You can also just load them into Paratext and work with them if there is any clean-up necessary.

**Comment by BethedenMinistries** [comment]
ebible.org is a big piece of this puzzle as well.

**Comment by arrocke** [comment]
@BethedenMinistries fetch.bible has a ton of open Bibles already. I'm thinking we start there and see how far that gets us. Do you think there are important translations that are missing from fetch.bible that we need to consider an additional approach?

**Comment by arrocke** [comment]
The other major question is what do we do with the many translations that aren't complete? In this case is it better to have a fallback translation in a different language than not show a reference translation?

**Comment by BethedenMinistries** [comment]
The important thing would be to filter them to see how many are actually complete bibles and not just NT. I think it's fine to start with fetch.Bible and go from there. I think Jon has done a good job of curating what's out there.

**Comment by BethedenMinistries** [comment]
If there's only a partial translation in a language, I think it would be best just to use what it has, and then have something that notifies the user clearly that certain portions of the Bible don't have a free translation available.

**Comment by arrocke** [comment]
Ok, another question. What about languages with multiple translations? For example [Hausa](https://fetch.bible/content/bibles/#hau) has to translations one that is complete in the NT and one that has some OT.

Addison and I were thinking that we could allow a language to specify multiple translations for each language and then we could look at each in the list for a translation until we find one

**Comment by BethedenMinistries** [comment]
I like that idea. Yeah, the more we can combine different works to make it more helpful, the better.

**Comment by shadow-light** [comment]
Hi @arrocke , fetch.bible is still alpha but stabilising the API is a high priority for me and would hopefully happen by Jan/Feb.

One way to look at it is just as automatable access to what's on eBible, either as USFM or USX. But if you need anything that would benefit other developers too, I could add it to the HTML or TXT formats. I'm still thinking through how best to integrate morphology and lemmas etc into the platform.

**Comment by arrocke** [comment]
Hey thanks for jumping in here! We are currently using the TXT format to load reference translations in our interlinear translation interface and it is working well. So far, I think the biggest need is is the lemma data. We would use that to highlight which words in the translation are connected to the Hebrew word the translator is glossing.

**Comment by shadow-light** [comment]
Ok great, I'll let you know if I make progress on the lemmas. I'm not sure when that would be though.
