### ISSUE TITLE
user session and login

### ISSUE THREAD

**Issue by arrocke** [arrocke/gloss-translation#65]
## acceptance criteria
* As a user I can log in with an email and password
* I can also log out
* I can see my name in the dropdown menu in the top right
* My session is [secure](https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html). Most notably:
  * My password is salted and hashed
  * The session expires
  * The session renews automatically for longer run connections
  * The session is not remembered once I close

## notes
* This story won't have a way to create a user, so we will have to insert one into the database manually.
* Logging at this point won't change access

**Comment by Pertempto** [comment]
This probably should be marked "In Progress"?
