### ISSUE TITLE
wireframe translation interface

### ISSUE THREAD

**Issue by arrocke** [arrocke/gloss-translation#7]
## acceptance criteria
* display line with gloss translation
* verse selection
* lexicon information
* translator notes
* verse translation
* key term

**Comment by Pertempto** [comment]
To keep things linked and easy to find, [here is the figma design](https://www.figma.com/file/GYKTJWl1otgwpmA9ZLLthE/Gloss-Translation-App?node-id=942%3A182&t=jLBe6HejQ8ugkIdL-0)

**Comment by arrocke** [comment]
A few things left to address on this from the conversation today:
- [x] only show context when clicking on hebrew word
- [x] render biblical and lexicon text in serif font
- [x] word level comments (create new thread, add comments, resolve thread)
- [x] add translations to gloss breakdown
- [x] move chapter context to sidebar
