### ISSUE TITLE
Contributing documentation

### ISSUE THREAD

**Issue by arrocke** [arrocke/gloss-translation#74]
## acceptance criteria
* document the following
  * build setup - os, terminal, database, node version
  * development process
  * expectations for PRs
  * expectations for new issues
  * workflow for prioritization
  * new dependencies - best practice, budget
* issue templates for bugs, feature requests
* PR template
* docker containers - vagrant
* all of this should be easily accessible from the main readme

## stories
* #78 
* #79
* #80
* #81
* #82

**Comment by Pertempto** [comment]
Related to "expectations for PRs", we should include some kind of list of what conventional commit prefixes we use, and what they mean. Something like this: https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#type

**Comment by Pertempto** [comment]
Include docs about policy with locking down dependency versions in `package.json`, see [this](https://github.com/arrocke/gloss-translation/pull/77#discussion_r1191818990).

**Comment by Pertempto** [comment]
> Related to "expectations for PRs", we should include some kind of list of what conventional commit prefixes we use, and what they mean. Something like this: https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#type



> Include docs about policy with locking down dependency versions in `package.json`, see [this](https://github.com/arrocke/gloss-translation/pull/77#discussion_r1191818990).



I don't see that we ended up addressing either of these in `contributing.md`

**Comment by arrocke** [comment]
Good catch. I pushed up a commit to address those two
