### ISSUE TITLE
verse reference format

### ISSUE THREAD

**Issue by arrocke** [arrocke/gloss-translation#75]
Andrew has suggested that we also support the formats `book 1.1` and `book 1 1`. Presently, we only support the `:` separator for english, each language can have its own verse reference format.

## Proposed Format
What I'm wondering is if we can supply a standard format that handles more than one type of separator.

`<book> <chapter><separator><verse>`
* This will be reversed for RTL languages
* `book`: The localized book name. This can be shortened if the language supports it
* `chapter`: The chapter number using the number format of the language
* `separator`: Either `:`, `.`, `,`, or ` `
* `verse`: The verse number using the number format of the language

## Questions
Does this format work in all of the gateway languages?
What other separators do we need to support?
Can we get examples from all of the gateway languages?

**Comment by arrocke** [comment]
@BethedenMinistries @LouKehler I'd be open to feedback on this

**Comment by BethedenMinistries** [comment]
I also suggest having a comma as separator.
