### ISSUE TITLE
vagrant setup for easy development

### ISSUE THREAD

**Issue by arrocke** [arrocke/gloss-translation#83]
## acceptance criteria
* setup a vagrantfile to spin up a development environment that has the right node environment, and a postgres database with seed data already set up
* document this in contributing documentation

**Comment by ilearner777** [comment]
I put the following request into chatGPT:
```
How do you setup a vagrant file to a create a windows 11 development environment that will perform the following tasks:
1. Install Node.js 18
2. In a terminal run: npm install
3. In a terminal run: npm i -g nx
4. Install postgresql version 14 (latest version).
5. Create database for the project. 
6. Create new file: ./packages/api/.env.local
7. Create new file: ./packages/db/.env.local
8. Add environment variable: DATABASE_URL to both files above to the postgres connection string. Here is a template you can use:
DATABASE_URL=postgres://{user}:{password}@{hostname}:{port}/{database-name}
9.  In a terminal run: nx prisma db migrate reset
10. In a terminal run: pg_restore -Fc --format=custom --dbname=<connection-string> data/seed.dump
```

This was response:

To set up a Vagrantfile for a Windows 11 development environment with the specified tasks, you can follow these steps:
```
    Create a directory for your Vagrant project and navigate to it in your terminal.

    Initialize a new Vagrant environment:

bash

vagrant init

    Edit the Vagrantfile to configure your Windows 11 environment:

ruby

Vagrant.configure("2") do |config|
  config.vm.box = "your-windows11-box"  # Replace with the Windows 11 box name or URL

  # Forward ports if needed
  config.vm.network "forwarded_port", guest: 80, host: 8080  # Example port forwarding

  # Set up provisioning script
  config.vm.provision "shell", inline: <<-SHELL
    # Install Node.js 18
    choco install nodejs-lts

    # Navigate to the project directory
    cd /path/to/your/project

    # Install npm packages
    npm install
    npm install -g nx

    # Install PostgreSQL 14
    choco install postgresql

    # Create database for the project
    psql -U postgres -c "CREATE DATABASE your-database-name"

    # Create .env.local files and add DATABASE_URL
    echo "DATABASE_URL=postgres://user:password@hostname:port/your-database-name" > ./packages/api/.env.local
    echo "DATABASE_URL=postgres://user:password@hostname:port/your-database-name" > ./packages/db/.env.local

    # Run database migrations
    nx prisma db migrate reset

    # Restore data from seed.dump (replace <connection-string>)
    pg_restore -Fc --format=custom --dbname=postgres://user:password@hostname:port/your-database-name data/seed.dump
  SHELL
end

Make sure to replace "your-windows11-box", /path/to/your/project, and other placeholders with the appropriate values for your setup.

    Save the Vagrantfile and exit the text editor.

    Start the Vagrant virtual machine:

bash

vagrant up

This will create and provision your Windows 11 development environment.

    Once the setup is complete, you can access the virtual machine by running:

bash

vagrant ssh

Now you should have a Windows 11 development environment with the specified tasks automated in your Vagrant setup. Make sure to adapt the paths, package names, and other details to match your project's configuration.
```
Is this what you had in mind?
Is this still worth pursuing? 
I have also created an ubuntu version of above.

**Comment by arrocke** [comment]
That's roughly the idea we are going for. I can't speak to the accuracy of the vagrant config because it's been a while since I used vagrant. I would do it on ubuntu rather than windows. That's better for this kind of work. The end goal is that you can spin up a container on your computer and get the entire development environment without having to set much up. Feel free to give it a go, but I won't be able to give much advice unless I do the research myself

**Comment by ilearner777** [comment]
If you wish, you can assign it to me and I will do some research and see if I can get it to work.

**Comment by arrocke** [comment]
Have at it!

**Comment by ilearner777** [comment]
How do I change the status of this issue to `in progress`?

**Comment by arrocke** [comment]
In the sidebar on the right there is a project section. It has a dropdown to change it to in progress. Can you see that or just me?

**Comment by ilearner777** [comment]
It is view only for me.
![image](https://github.com/arrocke/gloss-translation/assets/141659916/6ceb85f6-cad4-4ec9-ae11-33bdd538daaf)

**Comment by ilearner777** [comment]
Should we install the Ubuntu desktop in this install?

**Comment by arrocke** [comment]
We shouldn't need it because the purpose of vagrant is to be able to run terminal commands in another OS environment

**Comment by ilearner777** [comment]
should we set up any port forwarding?  It does set up a default of 80 and 8080.

**Comment by arrocke** [comment]
We are going to want port forwarding for the api, and web servers as well as the database so we can connect tools like pgadmin

**Comment by ilearner777** [comment]
Right now I am working on vagrantfile using VirtualBox. Vagrant also supports Hyper-V and vmware. Is VirtualBox sufficient for our project or should I investigate the other 2 providers?  Each provider will likely require a different Vagrantfile.

**Comment by arrocke** [comment]
VirtualBox should work for our use case. It's cross platform and free. If we need to support another VM, we can cross that bridge later

**Comment by ilearner777** [comment]
# Progress Update:

## Executive Overview
- Created a fully functional Ubuntu VM environment on Windows 11 Home Edition. 
- Able to access guest db via pgAdmin
- Able to access API app via host web browser
- However was not able to get the Web application to work on host web browser.

## Implemented Environment
- Host: Windows 11 Home Edition
- VirtualBox: *generic/ubuntu2204*
- Folder sharing using *rsync* (had issues running `npm install` with default virtualbox sharing due to symbolic issues.)

## Steps Completed
- Installed Vagrant
- Installed VirtualBox
- Installed box: *generic/ubuntu2204*
- Installed vagrant plugin: *vagrant-rsync-back*
- Created fully functional Vagrantfile
- node environment is fully functional on spin up
- Can access guest db via pgAdmin
- Can access guest API website via external web brower

## Issue
- For some unknown reason I am not able to access web application via external web browser
- Error messages are:
```
error "The remote device or resource won't accept the connection"
```
```
The connection to the server was reset while the page was loading.
```
- Repo works in my native windows environment but fails in guest environment.
- Not sure if my O/S is an issue as I have only Win home edition. Perhaps this will work in Win Pro edition or Mac.

## Next steps
We can release it on an *as-basis* with suggests for follow-up or improvements

## Suggested improvements
- Implement nfs instead of rsync. This is a little more complex on Windows

Please advise how I should proceed.

**Comment by arrocke** [comment]
Can you open a PR so we can take a look?

**Comment by ilearner777** [comment]
With the help of one of my sons, we were able to resolve the web issue. The issue had to do with the way the web app was loading. I believe localhost had loopback to 127.0.0.1 which caused it to reject request from host. To resolve we added line: `"host": "0.0.0.0"` to the `project.json` file as shown below:

```json
"serve": {
      "executor": "@nx/webpack:dev-server",
      "defaultConfiguration": "development",
      "options": {
        "buildTarget": "web:build",
        "hmr": true,
        "host": "0.0.0.0",
        "port": 4200
      },
```
Now we can access the web app at `localhost:4205`.  However, now when it loads I get 9 runtime errors.  The 1st one is shown below:

```text
TypeError
Failed to fetch
Call Stack
 ApiClient.request
  main.js:220:28
 ApiClient.get
  main.js:237:33
 Verses.findById
  main.js:608:24
 Object.queryFn
  main.js:3567:80
 Object.fetchFn [as fn]
  vendor.js:76818:27
 run
  vendor.js:77939:31
 createRetryer
  vendor.js:77987:5
 Query.fetch
  vendor.js:76873:45
 QueryClient.fetchQuery
  vendor.js:77620:68
 QueryClient.ensureQueryData
  vendor.js:77493:60
```

Inspector shows the following:

```text
request.js:44     GET http://localhost:4205/locales/en/translation.json 404 (Not Found)
```

Let me know if this is something I can resolve or should I push what I have to a PR?

**Comment by arrocke** [comment]
All of this conversation should be in a PR so that we can see the code changes when you have questions. Can you repost this last comment in the PR? I look forward to seeing your changes

**Comment by arrocke** [comment]
We ended up not doing this because we ran into a bunch of issues.
