### ISSUE TITLE
More accessible place for interface language

### ISSUE THREAD

**Issue by arrocke** [arrocke/gloss-translation#95]
Right now the interface language switcher is in the profile dropdown, which is hard to find and non-existing if you aren't logged in. We need to move this to a more visible place.

I'm thinking we add a footer and put this there as well as maybe consider automatically showing the language selector when you land on the site for the first time

**Comment by Pertempto** [comment]
@arrocke I would suggest bumping this up in priority a bit. As we test different features in RTL mode, it's inconvenient to have to use the profile dropdown. Especially when you realize that you got signed out. 

I would be interested in attempting to implement it.

**Comment by arrocke** [comment]
Yes, I think I agree. Feel free to pick up when you want

**Comment by Pertempto** [comment]
Do you have any common patterns/ideas on how to detect if this is the first time a user has accessed the site?

**Comment by Pertempto** [comment]
Should I just add an extra item to local storage that flags that they've been here before?

**Comment by arrocke** [comment]
i18next already used a local storage property. If not defined, it will make an educated guess. Before i18next loads we can check ourselves, and show the modal if the local storage prop isn't defined. Then the modal will default to i18next's guess
